
// Copyright 2012 Google Inc. All rights reserved.
(function(){

var data = {
"resource": {
  "version":"1",

  "macros":[],
  "tags":[],
  "predicates":[],
  "rules":[]
},
"runtime":[
[],[]
]



};
var aa,ba="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},da;if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var ea;a:{var fa={nf:!0},ia={};try{ia.__proto__=fa;ea=ia.nf;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ja=da,la=this||self,ma=/^[\w+/_-]+[=]{0,2}$/,oa=null;var pa=function(){},qa=function(a){return"function"==typeof a},f=function(a){return"string"==typeof a},ra=function(a){return"number"==typeof a&&!isNaN(a)},ua=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},t=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},va=function(a,b){if(a&&ua(a))for(var c=0;c<a.length;c++)if(a[c]&&b(a[c]))return a[c]},wa=function(a,b){if(!ra(a)||
!ra(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},ya=function(a,b){for(var c=new xa,d=0;d<a.length;d++)c.set(a[d],!0);for(var e=0;e<b.length;e++)if(c.get(b[e]))return!0;return!1},za=function(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(c,a[c])},Aa=function(a){return Math.round(Number(a))||0},Ca=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Da=function(a){var b=[];if(ua(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},Ea=function(a){return a?
a.replace(/^\s+|\s+$/g,""):""},Fa=function(){return(new Date).getTime()},xa=function(){this.prefix="gtm.";this.values={}};xa.prototype.set=function(a,b){this.values[this.prefix+a]=b};xa.prototype.get=function(a){return this.values[this.prefix+a]};xa.prototype.contains=function(a){return void 0!==this.get(a)};
var Ga=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},Ha=function(a){var b=!1;return function(){if(!b)try{a()}catch(c){}b=!0}},Ia=function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},Ja=function(a){for(var b in a)if(a.hasOwnProperty(b))return!0;return!1},Ka=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},La=function(a,b){for(var c={},d=c,e=a.split("."),g=0;g<e.length-1;g++)d=d[e[g]]={};d[e[e.length-1]]=b;return c};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Ma=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Na=function(a){if(null==a)return String(a);var b=Ma.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Oa=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Pa=function(a){if(!a||"object"!=Na(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Oa(a,"constructor")&&!Oa(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Oa(a,b)},B=function(a,b){var c=b||("array"==Na(a)?[]:{}),d;for(d in a)if(Oa(a,d)){var e=a[d];"array"==Na(e)?("array"!=Na(c[d])&&(c[d]=[]),c[d]=B(e,c[d])):Pa(e)?(Pa(c[d])||(c[d]={}),c[d]=B(e,c[d])):c[d]=e}return c};var ob;
var pb=[],qb=[],rb=[],tb=[],ub=[],vb={},wb,xb,yb,zb=function(a,b){var c={};c["function"]="__"+a;for(var d in b)b.hasOwnProperty(d)&&(c["vtp_"+d]=b[d]);return c},Ab=function(a,b){var c=a["function"];if(!c)throw Error("Error: No function name given for function call.");var d=vb[c],e={},g;for(g in a)a.hasOwnProperty(g)&&0===g.indexOf("vtp_")&&(e[void 0!==d?g:g.substr(4)]=a[g]);return void 0!==d?d(e):ob(c,e,b)},Db=function(a,b,c){c=c||[];var d={},e;for(e in a)a.hasOwnProperty(e)&&(d[e]=Bb(a[e],b,c));
return d},Eb=function(a){var b=a["function"];if(!b)throw"Error: No function name given for function call.";var c=vb[b];return c?c.priorityOverride||0:0},Bb=function(a,b,c){if(ua(a)){var d;switch(a[0]){case "function_id":return a[1];case "list":d=[];for(var e=1;e<a.length;e++)d.push(Bb(a[e],b,c));return d;case "macro":var g=a[1];if(c[g])return;var h=pb[g];if(!h||b.Gc(h))return;c[g]=!0;try{var k=Db(h,b,c);k.vtp_gtmEventId=b.id;d=Ab(k,b);yb&&(d=yb.Rf(d,k))}catch(y){b.ce&&b.ce(y,Number(g)),d=!1}c[g]=
!1;return d;case "map":d={};for(var l=1;l<a.length;l+=2)d[Bb(a[l],b,c)]=Bb(a[l+1],b,c);return d;case "template":d=[];for(var m=!1,n=1;n<a.length;n++){var q=Bb(a[n],b,c);xb&&(m=m||q===xb.yb);d.push(q)}return xb&&m?xb.Uf(d):d.join("");case "escape":d=Bb(a[1],b,c);if(xb&&ua(a[1])&&"macro"===a[1][0]&&xb.Bg(a))return xb.Mg(d);d=String(d);for(var u=2;u<a.length;u++)Qa[a[u]]&&(d=Qa[a[u]](d));return d;case "tag":var p=a[1];if(!tb[p])throw Error("Unable to resolve tag reference "+p+".");return d={Td:a[2],
index:p};case "zb":var r={arg0:a[2],arg1:a[3],ignore_case:a[5]};r["function"]=a[1];var v=Fb(r,b,c),w=!!a[4];return w||2!==v?w!==(1===v):null;default:throw Error("Attempting to expand unknown Value type: "+a[0]+".");}}return a},Fb=function(a,b,c){try{return wb(Db(a,b,c))}catch(d){JSON.stringify(a)}return 2};var Gb=function(){var a=function(b){return{toString:function(){return b}}};return{jd:a("convert_case_to"),kd:a("convert_false_to"),ld:a("convert_null_to"),md:a("convert_true_to"),nd:a("convert_undefined_to"),sh:a("debug_mode_metadata"),la:a("function"),bf:a("instance_name"),cf:a("live_only"),df:a("malware_disabled"),ef:a("metadata"),uh:a("original_vendor_template_id"),ff:a("once_per_event"),Gd:a("once_per_load"),Hd:a("setup_tags"),Id:a("tag_id"),Jd:a("teardown_tags")}}();var Hb=null,Kb=function(a){function b(q){for(var u=0;u<q.length;u++)d[q[u]]=!0}var c=[],d=[];Hb=Ib(a);for(var e=0;e<qb.length;e++){var g=qb[e],h=Jb(g);if(h){for(var k=g.add||[],l=0;l<k.length;l++)c[k[l]]=!0;b(g.block||[])}else null===h&&b(g.block||[])}for(var m=[],n=0;n<tb.length;n++)c[n]&&!d[n]&&(m[n]=!0);return m},Jb=function(a){for(var b=a["if"]||[],c=0;c<b.length;c++){var d=Hb(b[c]);if(0===d)return!1;if(2===d)return null}for(var e=a.unless||[],g=0;g<e.length;g++){var h=Hb(e[g]);if(2===h)return null;
if(1===h)return!1}return!0},Ib=function(a){var b=[];return function(c){void 0===b[c]&&(b[c]=Fb(rb[c],a));return b[c]}};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */
var D=window,F=document,Sb=navigator,Tb=F.currentScript&&F.currentScript.src,Ub=function(a,b){var c=D[a];D[a]=void 0===c?b:c;return D[a]},Vb=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},Wb=function(a,b,c){var d=F.createElement("script");d.type="text/javascript";d.async=!0;d.src=a;Vb(d,b);c&&(d.onerror=c);var e;if(null===oa)b:{var g=la.document,h=g.querySelector&&g.querySelector("script[nonce]");
if(h){var k=h.nonce||h.getAttribute("nonce");if(k&&ma.test(k)){oa=k;break b}}oa=""}e=oa;e&&d.setAttribute("nonce",e);var l=F.getElementsByTagName("script")[0]||F.body||F.head;l.parentNode.insertBefore(d,l);return d},Xb=function(){if(Tb){var a=Tb.toLowerCase();if(0===a.indexOf("https://"))return 2;if(0===a.indexOf("http://"))return 3}return 1},Yb=function(a,b){var c=F.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";var d=F.body&&F.body.lastChild||
F.body||F.head;d.parentNode.insertBefore(c,d);Vb(c,b);void 0!==a&&(c.src=a);return c},Zb=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a;return d},$b=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},ac=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)},G=function(a){D.setTimeout(a,0)},bc=function(a,b){return a&&
b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},cc=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},dc=function(a){var b=F.createElement("div");b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},ec=function(a,b,c){c=c||100;for(var d={},e=0;e<b.length;e++)d[b[e]]=!0;for(var g=a,h=0;g&&h<=c;h++){if(d[String(g.tagName).toLowerCase()])return g;
g=g.parentElement}return null},fc=function(a,b){var c=a[b];c&&"string"===typeof c.animVal&&(c=c.animVal);return c};var I={ka:"_ee",cc:"event_callback",Ra:"event_timeout",w:"gtag.config",O:"allow_ad_personalization_signals",U:"cookie_expires",Pa:"cookie_update",Aa:"session_duration",V:"user_properties"};
I.ac="page_view",I.Be="user_engagement",I.Ce="allow_custom_scripts",I.De="allow_display_features",I.Ee="allow_enhanced_conversions",I.sb="client_id",I.T="cookie_domain",I.tb="cookie_name",I.xa="cookie_path",I.ca="currency",I.Qa="custom_params",I.He="custom_map",I.ic="groups",I.ya="language",I.Ge="country",I.th="non_interaction",I.Va="page_location",I.Wa="page_referrer",I.kc="page_title",I.Xa="send_page_view",I.za="send_to",I.mc="session_engaged",I.wb="session_id",I.nc="session_number",I.Ze="tracking_id",
I.ja="linker",I.Sa="accept_incoming",I.F="domains",I.Ua="url_position",I.Ta="decorate_forms",I.Bd="phone_conversion_number",I.zd="phone_conversion_callback",I.Ad="phone_conversion_css_class",I.Cd="phone_conversion_options",I.Ve="phone_conversion_ids",I.Ue="phone_conversion_country_code",I.od="aw_remarketing",I.pd="aw_remarketing_only",I.Z="value",I.We="quantity",I.Ke="affiliation",I.Oe="tax",I.Ne="shipping",I.bc="list_name",I.xd="checkout_step",I.wd="checkout_option",I.Le="coupon",I.Me="promotions",
I.Ya="transaction_id",I.$a="user_id",I.wa="conversion_linker",I.va="conversion_cookie_prefix",I.P="cookie_prefix",I.Y="items",I.td="aw_merchant_id",I.rd="aw_feed_country",I.sd="aw_feed_language",I.qd="discount",I.vd="disable_merchant_reported_purchases",I.jc="new_customer",I.ud="customer_lifetime_value",I.Je="dc_natural_search",I.Ie="dc_custom_params",I.$e="trip_type",I.yd="passengers",I.Se="method",I.Ye="search_term",I.Fe="content_type",I.Te="optimize_id",I.Pe="experiments",I.vb="google_signals",
I.hc="google_tld",I.xb="update",I.gc="firebase_id",I.ub="ga_restrict_domain",I.fc="event_settings",I.Xe="screen_name",I.Re="_x_19",I.Qe="_x_20",I.Za="transport_url",I.af=[I.O,I.T,I.U,I.tb,I.xa,I.P,I.Pa,I.Qa,I.cc,I.fc,I.Ra,I.ub,I.vb,I.hc,I.ic,I.ja,I.za,I.Xa,I.Aa,I.xb,I.V,I.Za],I.Ed=[I.Va,I.Wa,I.kc,I.ya,I.Xe,I.$a,I.gc],I.gd=[I.za,I.od,I.pd,I.Qa,I.Xa,I.ya,I.Z,I.ca,I.Ya,I.$a,I.wa,I.va,I.P,I.Va,I.Wa,I.Bd,I.zd,I.Ad,I.Cd,I.Y,I.td,I.rd,I.sd,I.qd,I.vd,I.jc,I.ud,I.O,I.xb,I.gc];var uc=/[A-Z]+/,vc=/\s/,wc=function(a){if(f(a)&&(a=Ea(a),!vc.test(a))){var b=a.indexOf("-");if(!(0>b)){var c=a.substring(0,b);if(uc.test(c)){for(var d=a.substring(b+1).split("/"),e=0;e<d.length;e++)if(!d[e])return;return{id:a,prefix:c,containerId:c+"-"+d[0],h:d}}}}},yc=function(a){for(var b={},c=0;c<a.length;++c){var d=wc(a[c]);d&&(b[d.id]=d)}xc(b);var e=[];za(b,function(g,h){e.push(h)});return e};
function xc(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];"AW"===d.prefix&&d.h[1]&&b.push(d.containerId)}for(var e=0;e<b.length;++e)delete a[b[e]]};var zc={},Ac=null,Bc=Math.random();zc.m="UA-108653085-1";zc.Cb="av9";var Cc={__cl:!0,__ecl:!0,__ehl:!0,__evl:!0,__fal:!0,__fil:!0,__fsl:!0,__hl:!0,__jel:!0,__lcl:!0,__sdl:!0,__tl:!0,__ytl:!0,__paused:!0,__tg:!0},Dc="www.googletagmanager.com/gtm.js";Dc="www.googletagmanager.com/gtag/js";var Ec=Dc,Fc=null,Gc=null,Hc=null,Ic="//www.googletagmanager.com/a?id="+zc.m+"&cv=1",Jc={},Kc={},Lc=function(){var a=Ac.sequence||0;Ac.sequence=a+1;return a};var Mc={},J=function(a,b){Mc[a]=Mc[a]||[];Mc[a][b]=!0},Nc=function(a){for(var b=[],c=Mc[a]||[],d=0;d<c.length;d++)c[d]&&(b[Math.floor(d/6)]^=1<<d%6);for(var e=0;e<b.length;e++)b[e]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_".charAt(b[e]||0);return b.join("")};
var Oc=function(){return"&tc="+tb.filter(function(a){return a}).length},Rc=function(){Pc||(Pc=D.setTimeout(Qc,500))},Qc=function(){Pc&&(D.clearTimeout(Pc),Pc=void 0);void 0===Sc||Tc[Sc]&&!Uc&&!Vc||(Wc[Sc]||Xc.Dg()||0>=Yc--?(J("GTM",1),Wc[Sc]=!0):(Xc.Xg(),Zb(Zc()),Tc[Sc]=!0,ad=Vc=Uc=""))},Zc=function(){var a=Sc;if(void 0===a)return"";var b=Nc("GTM"),c=Nc("TAGGING");return[bd,Tc[a]?"":"&es=1",cd[a],b?"&u="+b:"",c?"&ut="+c:"",Oc(),Uc,Vc,ad,"&z=0"].join("")},dd=function(){return[Ic,"&v=3&t=t","&pid="+
wa(),"&rv="+zc.Cb].join("")},ed="0.005000">Math.random(),bd=dd(),fd=function(){bd=dd()},Tc={},Uc="",Vc="",ad="",Sc=void 0,cd={},Wc={},Pc=void 0,Xc=function(a,b){var c=0,d=0;return{Dg:function(){if(c<a)return!1;Fa()-d>=b&&(c=0);return c>=a},Xg:function(){Fa()-d>=b&&(c=0);c++;d=Fa()}}}(2,1E3),Yc=1E3,gd=function(a,b){if(ed&&!Wc[a]&&Sc!==a){Qc();Sc=a;Uc="";var c;c=0===b.indexOf("gtm.")?encodeURIComponent(b):"*";cd[a]="&e="+c+"&eid="+a;Rc()}},hd=function(a,b,c){if(ed&&!Wc[a]&&b){a!==Sc&&
(Qc(),Sc=a);var d=String(b[Gb.la]||"").replace(/_/g,"");0===d.indexOf("cvt")&&(d="cvt");var e=c+d;Uc=Uc?Uc+"."+e:"&tr="+e;Rc();2022<=Zc().length&&Qc()}},id=function(a,b,c){if(ed&&!Wc[a]){a!==Sc&&(Qc(),Sc=a);var d=c+b;Vc=Vc?Vc+"."+d:"&epr="+d;Rc();2022<=Zc().length&&Qc()}};var jd={},kd=new xa,ld={},md={},pd={name:"dataLayer",set:function(a,b){B(La(a,b),ld);nd()},get:function(a){return od(a,2)},reset:function(){kd=new xa;ld={};nd()}},od=function(a,b){if(2!=b){var c=kd.get(a);if(ed){var d=qd(a);c!==d&&J("GTM",5)}return c}return qd(a)},qd=function(a,b,c){var d=a.split("."),e=!1,g=void 0;var h=function(k,l){for(var m=0;void 0!==k&&m<d.length;m++){if(null===k)return!1;k=k[d[m]]}return void 0!==k||1<m?k:l.length?h(rd(l.pop()),l):sd(d)};
e=!0;g=h(ld.eventModel,[b,c]);return e?g:sd(d)},sd=function(a){for(var b=ld,c=0;c<a.length;c++){if(null===b)return!1;if(void 0===b)break;b=b[a[c]]}return b};var rd=function(a){if(a){var b=sd(["gtag","targets",a]);return Pa(b)?b:void 0}},td=function(a,b){function c(g){g&&za(g,function(h){d[h]=null})}var d={};c(ld);delete d.eventModel;c(rd(a));c(rd(b));c(ld.eventModel);var e=[];za(d,function(g){e.push(g)});return e};
var ud=function(a,b){md.hasOwnProperty(a)||(kd.set(a,b),B(La(a,b),ld),nd())},nd=function(a){za(md,function(b,c){kd.set(b,c);B(La(b,void 0),ld);B(La(b,c),ld);a&&delete md[b]})},vd=function(a,b,c){jd[a]=jd[a]||{};var d=1!==c?qd(b):kd.get(b);"array"===Na(d)||"object"===Na(d)?jd[a][b]=B(d):jd[a][b]=d},wd=function(a,b){if(jd[a])return jd[a][b]};var xd=function(){var a=!1;return a};var P=function(a,b,c,d){return(2===yd()||d||"http:"!=D.location.protocol?a:b)+c},yd=function(){var a=Xb(),b;if(1===a)a:{var c=Ec;c=c.toLowerCase();for(var d="https://"+c,e="http://"+c,g=1,h=F.getElementsByTagName("script"),k=0;k<h.length&&100>k;k++){var l=h[k].src;if(l){l=l.toLowerCase();if(0===l.indexOf(e)){b=3;break a}1===g&&0===l.indexOf(d)&&(g=2)}}b=g}else b=a;return b};
var Ad=function(a,b,c){if(D[a.functionName])return b.Oc&&G(b.Oc),D[a.functionName];var d=zd();D[a.functionName]=d;if(a.Fb)for(var e=0;e<a.Fb.length;e++)D[a.Fb[e]]=D[a.Fb[e]]||zd();a.Pb&&void 0===D[a.Pb]&&(D[a.Pb]=c);Wb(P("https://","http://",a.Yc),b.Oc,b.Hg);return d},zd=function(){var a=function(){a.q=a.q||[];a.q.push(arguments)};return a},Bd={functionName:"_googWcmImpl",Pb:"_googWcmAk",Yc:"www.gstatic.com/wcm/loader.js"},Cd={functionName:"_gaPhoneImpl",Pb:"ga_wpid",Yc:"www.gstatic.com/gaphone/loader.js"},
Dd={ye:"",jf:"1"},Ed={functionName:"_googCallTrackingImpl",Fb:[Cd.functionName,Bd.functionName],Yc:"www.gstatic.com/call-tracking/call-tracking_"+(Dd.ye||Dd.jf)+".js"},Fd={},Gd=function(a,b,c,d){J("GTM",22);if(c){d=d||{};var e=Ad(Bd,d,a),g={ak:a,cl:b};void 0===d.ba&&(g.autoreplace=c);e(2,d.ba,g,c,0,new Date,d.options)}},Hd=function(a,b,c){J("GTM",23);if(b){c=c||{};var d=Ad(Cd,c,a),e={};void 0!==c.ba?e.receiver=c.ba:e.replace=b;e.ga_wpid=a;e.destination=b;d(2,new Date,
e)}},Id=function(a,b,c,d){J("GTM",21);if(b&&c){d=d||{};for(var e={countryNameCode:c,destinationNumber:b,retrievalTime:new Date},g=0;g<a.length;g++){var h=a[g];Fd[h.id]||(h&&"AW"===h.prefix&&!e.adData&&2<=h.h.length?(e.adData={ak:h.h[0],cl:h.h[1]},Fd[h.id]=!0):h&&"UA"===h.prefix&&!e.gaData&&(e.gaData={gaWpid:h.containerId},Fd[h.id]=!0))}(e.gaData||e.adData)&&Ad(Ed,d)(d.ba,e,d.options)}},Jd=function(){var a=!1;
return a},Kd=function(a){if(a)if(xd()){}else{if(f(a)){var b=wc(a);if(!b)return;a=b}var c=function(y){return qd(y,a.containerId,a.id)},d=void 0;var e=!1,g=c(I.Ve);if(g&&ua(g)){d=[];for(var h=0;h<g.length;h++){var k=wc(g[h]);k&&(d.push(k),(a.id===k.id||a.id===a.containerId&&a.containerId===k.containerId)&&(e=!0))}}if(d&&!e)return;
var l=c(I.Bd),m;if(l){m=ua(l)?l:[l];var n=c(I.zd),q=c(I.Ad),u=c(I.Cd),p=c(I.Ue),r=n||q,v=1;"UA"!==a.prefix||d||(v=5);for(var w=0;w<m.length;w++)w<v&&(d?Id(d,m[w],p,{ba:r,options:u}):"AW"===a.prefix&&a.h[1]?Jd()?Id([a],m[w],p||"US",{ba:r,options:u}):Gd(a.h[0],a.h[1],m[w],{ba:r,options:u}):"UA"===a.prefix&&(Jd()?Id([a],m[w],p||"US",{ba:r}):Hd(a.containerId,m[w],{ba:r})))}}};var Nd=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),Od={cl:["ecl"],customPixels:["nonGooglePixels"],ecl:["cl"],ehl:["hl"],hl:["ehl"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},Pd={cl:["ecl"],customPixels:["customScripts","html"],
ecl:["cl"],ehl:["hl"],hl:["ehl"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels","customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},Qd="google customPixels customScripts html nonGooglePixels nonGoogleScripts nonGoogleIframes".split(" ");
var Sd=function(a){Kc.pntr=Kc.pntr||["nonGoogleScripts"];Kc.snppx=Kc.snppx||["nonGoogleScripts"];Kc.qpx=Kc.qpx||["nonGooglePixels"];var b=od("gtm.whitelist");b&&J("GTM",9);b="google gtagfl lcl zone oid op".split(" ");
var c=b&&Ka(Da(b),Od),d=od("gtm.blacklist");d||(d=od("tagTypeBlacklist"))&&J("GTM",3);d?J("GTM",8):d=[];Rd()&&(d=Da(d),d.push("nonGooglePixels","nonGoogleScripts","sandboxedScripts"));0<=t(Da(d),"google")&&J("GTM",2);var e=d&&Ka(Da(d),Pd),g={};return function(h){var k=h&&h[Gb.la];if(!k||"string"!=typeof k)return!0;k=k.replace(/^_*/,"");if(void 0!==g[k])return g[k];
var l=Kc[k]||[],m=a(k,l);if(b){var n;if(n=m)a:{if(0>t(c,k))if(l&&0<l.length)for(var q=0;q<l.length;q++){if(0>t(c,l[q])){J("GTM",11);n=!1;break a}}else{n=!1;break a}n=!0}m=n}var u=!1;if(d){var p=0<=t(e,k);if(p)u=p;else{var r=ya(e,l||[]);r&&J("GTM",10);u=r}}var v=!m||u;v||!(0<=t(l,"sandboxedScripts"))||c&&-1!==t(c,"sandboxedScripts")||(v=ya(e,Qd));return g[k]=v}},Rd=function(){return Nd.test(D.location&&D.location.hostname)};var Td={Rf:function(a,b){b[Gb.jd]&&"string"===typeof a&&(a=1==b[Gb.jd]?a.toLowerCase():a.toUpperCase());b.hasOwnProperty(Gb.ld)&&null===a&&(a=b[Gb.ld]);b.hasOwnProperty(Gb.nd)&&void 0===a&&(a=b[Gb.nd]);b.hasOwnProperty(Gb.md)&&!0===a&&(a=b[Gb.md]);b.hasOwnProperty(Gb.kd)&&!1===a&&(a=b[Gb.kd]);return a}};var Ud={active:!0,isWhitelisted:function(){return!0}},Vd=function(a){var b=Ac.zones;!b&&a&&(b=Ac.zones=a());return b};var Wd=!1,Xd=0,Yd=[];function Zd(a){if(!Wd){var b=F.createEventObject,c="complete"==F.readyState,d="interactive"==F.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){Wd=!0;for(var e=0;e<Yd.length;e++)G(Yd[e])}Yd.push=function(){for(var g=0;g<arguments.length;g++)G(arguments[g]);return 0}}}function $d(){if(!Wd&&140>Xd){Xd++;try{F.documentElement.doScroll("left"),Zd()}catch(a){D.setTimeout($d,50)}}}var ae=function(a){Wd?a():Yd.push(a)};var be={},ce={},de=function(a,b,c,d){if(!ce[a]||Cc[b]||"__zone"===b)return-1;var e={};Pa(d)&&(e=B(d,e));e.id=c;e.status="timeout";return ce[a].tags.push(e)-1},ee=function(a,b,c,d){if(ce[a]){var e=ce[a].tags[b];e&&(e.status=c,e.executionTime=d)}};function fe(a){for(var b=be[a]||[],c=0;c<b.length;c++)b[c]();be[a]={push:function(d){d(zc.m,ce[a])}}}
var ie=function(a,b,c){ce[a]={tags:[]};qa(b)&&ge(a,b);c&&D.setTimeout(function(){return fe(a)},Number(c));return he(a)},ge=function(a,b){be[a]=be[a]||[];be[a].push(Ha(function(){return G(function(){b(zc.m,ce[a])})}))};function he(a){var b=0,c=0,d=!1;return{add:function(){c++;return Ha(function(){b++;d&&b>=c&&fe(a)})},Af:function(){d=!0;b>=c&&fe(a)}}};var je=function(){function a(d){return!ra(d)||0>d?0:d}if(!Ac._li&&D.performance&&D.performance.timing){var b=D.performance.timing.navigationStart,c=ra(pd.get("gtm.start"))?pd.get("gtm.start"):0;Ac._li={cst:a(c-b),cbt:a(Gc-b)}}};var ne=!1,oe=function(){return D.GoogleAnalyticsObject&&D[D.GoogleAnalyticsObject]},pe=!1;
var qe=function(a){D.GoogleAnalyticsObject||(D.GoogleAnalyticsObject=a||"ga");var b=D.GoogleAnalyticsObject;if(D[b])D.hasOwnProperty(b)||J("GTM",12);else{var c=function(){c.q=c.q||[];c.q.push(arguments)};c.l=Number(new Date);D[b]=c}je();return D[b]},re=function(a,b,c,d){b=String(b).replace(/\s+/g,"").split(",");var e=oe();e(a+"require","linker");e(a+"linker:autoLink",b,c,d)};
var te=function(){},se=function(){return D.GoogleAnalyticsObject||"ga"};var ve=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;var we=/:[0-9]+$/,xe=function(a,b,c){for(var d=a.split("&"),e=0;e<d.length;e++){var g=d[e].split("=");if(decodeURIComponent(g[0]).replace(/\+/g," ")===b){var h=g.slice(1).join("=");return c?h:decodeURIComponent(h).replace(/\+/g," ")}}},Ae=function(a,b,c,d,e){b&&(b=String(b).toLowerCase());if("protocol"===b||"port"===b)a.protocol=ye(a.protocol)||ye(D.location.protocol);"port"===b?a.port=String(Number(a.hostname?a.port:D.location.port)||("http"==a.protocol?80:"https"==a.protocol?443:"")):"host"===b&&
(a.hostname=(a.hostname||D.location.hostname).replace(we,"").toLowerCase());var g=b,h,k=ye(a.protocol);g&&(g=String(g).toLowerCase());switch(g){case "url_no_fragment":h=ze(a);break;case "protocol":h=k;break;case "host":h=a.hostname.replace(we,"").toLowerCase();if(c){var l=/^www\d*\./.exec(h);l&&l[0]&&(h=h.substr(l[0].length))}break;case "port":h=String(Number(a.port)||("http"==k?80:"https"==k?443:""));break;case "path":a.pathname||a.hostname||J("TAGGING",1);h="/"==a.pathname.substr(0,1)?a.pathname:
"/"+a.pathname;var m=h.split("/");0<=t(d||[],m[m.length-1])&&(m[m.length-1]="");h=m.join("/");break;case "query":h=a.search.replace("?","");e&&(h=xe(h,e,void 0));break;case "extension":var n=a.pathname.split(".");h=1<n.length?n[n.length-1]:"";h=h.split("/")[0];break;case "fragment":h=a.hash.replace("#","");break;default:h=a&&a.href}return h},ye=function(a){return a?a.replace(":","").toLowerCase():""},ze=function(a){var b="";if(a&&a.href){var c=a.href.indexOf("#");b=0>c?a.href:a.href.substr(0,c)}return b},
Be=function(a){var b=F.createElement("a");a&&(b.href=a);var c=b.pathname;"/"!==c[0]&&(a||J("TAGGING",1),c="/"+c);var d=b.hostname.replace(we,"");return{href:b.href,protocol:b.protocol,host:b.host,hostname:d,pathname:c,search:b.search,hash:b.hash,port:b.port}};function Ge(a,b,c,d){var e=tb[a],g=He(a,b,c,d);if(!g)return null;var h=Bb(e[Gb.Hd],c,[]);if(h&&h.length){var k=h[0];g=Ge(k.index,{s:g,o:1===k.Td?b.terminate:g,terminate:b.terminate},c,d)}return g}
function He(a,b,c,d){function e(){if(g[Gb.df])k();else{var w=Db(g,c,[]),y=de(c.id,String(g[Gb.la]),Number(g[Gb.Id]),w[Gb.ef]),x=!1;w.vtp_gtmOnSuccess=function(){if(!x){x=!0;var A=Fa()-C;hd(c.id,tb[a],"5");ee(c.id,y,"success",A);h()}};w.vtp_gtmOnFailure=function(){if(!x){x=!0;var A=Fa()-C;hd(c.id,tb[a],"6");ee(c.id,y,"failure",A);k()}};w.vtp_gtmTagId=g.tag_id;
w.vtp_gtmEventId=c.id;hd(c.id,g,"1");var z=function(){var A=Fa()-C;hd(c.id,g,"7");ee(c.id,y,"exception",A);x||(x=!0,k())};var C=Fa();try{Ab(w,c)}catch(A){z(A)}}}var g=tb[a],h=b.s,k=b.o,l=b.terminate;if(c.Gc(g))return null;var m=Bb(g[Gb.Jd],c,[]);if(m&&m.length){var n=m[0],q=Ge(n.index,{s:h,o:k,terminate:l},c,d);if(!q)return null;h=q;k=2===n.Td?l:q}if(g[Gb.Gd]||g[Gb.ff]){var u=g[Gb.Gd]?ub:c.gh,p=h,r=k;if(!u[a]){e=Ha(e);var v=Ie(a,u,e);h=v.s;k=v.o}return function(){u[a](p,r)}}return e}
function Ie(a,b,c){var d=[],e=[];b[a]=Je(d,e,c);return{s:function(){b[a]=Ke;for(var g=0;g<d.length;g++)d[g]()},o:function(){b[a]=Le;for(var g=0;g<e.length;g++)e[g]()}}}function Je(a,b,c){return function(d,e){a.push(d);b.push(e);c()}}function Ke(a){a()}function Le(a,b){b()};var Oe=function(a,b){for(var c=[],d=0;d<tb.length;d++)if(a.kb[d]){var e=tb[d];var g=b.add();try{var h=Ge(d,{s:g,o:g,terminate:g},a,d);h?c.push({ve:d,je:Eb(e),bg:h}):(Me(d,a),g())}catch(l){g()}}b.Af();c.sort(Ne);for(var k=0;k<c.length;k++)c[k].bg();return 0<c.length};function Ne(a,b){var c,d=b.je,e=a.je;c=d>e?1:d<e?-1:0;var g;if(0!==c)g=c;else{var h=a.ve,k=b.ve;g=h>k?1:h<k?-1:0}return g}
function Me(a,b){if(!ed)return;var c=function(d){var e=b.Gc(tb[d])?"3":"4",g=Bb(tb[d][Gb.Hd],b,[]);g&&g.length&&c(g[0].index);hd(b.id,tb[d],e);var h=Bb(tb[d][Gb.Jd],b,[]);h&&h.length&&c(h[0].index)};c(a);}
var Pe=!1,Qe=function(a,b,c,d,e){if("gtm.js"==b){if(Pe)return!1;Pe=!0}gd(a,b);var g=ie(a,d,e);vd(a,"event",1);vd(a,"ecommerce",1);vd(a,"gtm");var h={id:a,name:b,Gc:Sd(c),kb:[],gh:[],ce:function(){J("GTM",6)}};h.kb=Kb(h);var k=Oe(h,g);
if(!k)return k;for(var l=0;l<h.kb.length;l++)if(h.kb[l]){var m=tb[l];if(m&&!Cc[String(m[Gb.la])])return!0}return!1};var Re=function(a,b){var c=zb(a,b);tb.push(c);return tb.length-1};var Se=/^https?:\/\/www\.googletagmanager\.com/,Te=function(){var a;return a},Ue=function(){var a=!1;return a};var Ve=function(){this.eventModel={};this.targetConfig={};this.containerConfig={};this.La={};this.globalConfig={};this.s=function(){};this.o=function(){}},We=function(a){var b=new Ve;b.eventModel=a;return b},Xe=function(a,b){a.targetConfig=b;return a},Ye=function(a,b){a.containerConfig=b;return a},Ze=function(a,b){a.La=b;return a},$e=function(a,b){a.globalConfig=b;return a},af=function(a,b){a.s=b;return a},bf=function(a,b){a.o=b;return a};
Ve.prototype.getWithConfig=function(a){if(void 0!==this.eventModel[a])return this.eventModel[a];if(void 0!==this.targetConfig[a])return this.targetConfig[a];if(void 0!==this.containerConfig[a])return this.containerConfig[a];if(void 0!==this.La[a])return this.La[a];if(void 0!==this.globalConfig[a])return this.globalConfig[a]};var cf={},df=["G"];cf.xe="";var ef=cf.xe.split(",");function ff(){var a=Ac;return a.gcq=a.gcq||new gf}
var hf=function(a,b,c){ff().register(a,b,c)},jf=function(a,b,c,d){ff().push("event",[b,a],c,d)},kf=function(a,b){ff().push("config",[a],b)},lf={},mf=function(){this.status=1;this.containerConfig={};this.targetConfig={};this.La={};this.ke=null;this.Zd=!1},nf=function(a,b,c,d,e){this.type=a;this.we=b;this.L=c||"";this.Gb=d;this.defer=e},gf=function(){this.Pd={};this.Yd={};this.fb=[]},of=function(a,b){var c=wc(b);return a.Pd[c.containerId]=a.Pd[c.containerId]||new mf},pf=function(a,b,c,d){if(d.L){var e=
of(a,d.L),g=e.ke;if(g){var h=B(c),k=B(e.targetConfig[d.L]),l=B(e.containerConfig),m=B(e.La),n=B(a.Yd),q=od("gtm.uniqueEventId"),u=wc(d.L).prefix,p=bf(af($e(Ze(Ye(Xe(We(h),k),l),m),n),function(){id(q,u,"2");}),function(){id(q,u,"3");});try{id(q,u,"1");3===g.length?g(b,d.we,p):4===g.length&&
g(d.L,b,d.we,p)}catch(r){id(q,u,"4");}}}};
gf.prototype.register=function(a,b,c){if(3!==of(this,a).status){of(this,a).ke=b;of(this,a).status=3;c&&(of(this,a).La=c);var d=wc(a),e=lf[d.containerId];if(void 0!==e){var g=Ac[d.containerId].bootstrap,h=d.prefix.toUpperCase();Ac[d.containerId]._spx&&(h=h.toLowerCase());var k=od("gtm.uniqueEventId"),l=h,m=Fa()-g;if(ed&&!Wc[k]){k!==Sc&&(Qc(),Sc=k);var n=l+"."+Math.floor(g-e)+"."+Math.floor(m);ad=ad?ad+","+n:"&cl="+n}delete lf[d.containerId]}this.flush()}};
gf.prototype.push=function(a,b,c,d){var e=Math.floor(Fa()/1E3);if(c){var g=wc(c),h;if(h=g){var k;if(k=1===of(this,c).status)a:{var l=g.prefix;k=!0}h=k}if(h&&(of(this,c).status=2,this.push("require",[],g.containerId),lf[g.containerId]=Fa(),!xd())){var m=encodeURIComponent(g.containerId),n=("http:"!=D.location.protocol?"https:":"http:")+
"//www.googletagmanager.com";Wb(n+"/gtag/js?id="+m+"&l=dataLayer&cx=c")}}this.fb.push(new nf(a,e,c,b,d));d||this.flush()};
gf.prototype.flush=function(a){for(var b=this;this.fb.length;){var c=this.fb[0];if(c.defer)c.defer=!1,this.fb.push(c);else switch(c.type){case "require":if(3!==of(this,c.L).status&&!a)return;break;case "set":za(c.Gb[0],function(l,m){B(La(l,m),b.Yd)});break;case "config":var d=c.Gb[0],e=!!d[I.xb];delete d[I.xb];var g=of(this,c.L),h=wc(c.L),k=h.containerId===h.id;e||(k?g.containerConfig={}:g.targetConfig[c.L]={});g.Zd&&e||pf(this,I.w,d,c);g.Zd=!0;delete d[I.ka];k?B(d,g.containerConfig):B(d,g.targetConfig[c.L]);
break;case "event":pf(this,c.Gb[1],c.Gb[0],c)}this.fb.shift()}};var qf=function(a,b,c){for(var d=[],e=String(b||document.cookie).split(";"),g=0;g<e.length;g++){var h=e[g].split("="),k=h[0].replace(/^\s*|\s*$/g,"");if(k&&k==a){var l=h.slice(1).join("=").replace(/^\s*|\s*$/g,"");l&&c&&(l=decodeURIComponent(l));d.push(l)}}return d},tf=function(a,b,c,d){var e=rf(a,d);if(1===e.length)return e[0].id;if(0!==e.length){e=sf(e,function(g){return g.Lb},b);if(1===e.length)return e[0].id;e=sf(e,function(g){return g.lb},c);return e[0]?e[0].id:void 0}};
function uf(a,b,c){var d=document.cookie;document.cookie=a;var e=document.cookie;return d!=e||void 0!=c&&0<=qf(b,e).indexOf(c)}
var xf=function(a,b,c,d,e,g){d=d||"auto";var h={path:c||"/"};e&&(h.expires=e);"none"!==d&&(h.domain=d);var k;a:{var l=b,m;if(void 0==l)m=a+"=deleted; expires="+(new Date(0)).toUTCString();else{g&&(l=encodeURIComponent(l));var n=l;n&&1200<n.length&&(n=n.substring(0,1200));l=n;m=a+"="+l}var q=void 0,u=void 0,p;for(p in h)if(h.hasOwnProperty(p)){var r=h[p];if(null!=r)switch(p){case "secure":r&&(m+="; secure");break;case "domain":q=r;break;default:"path"==p&&(u=r),"expires"==p&&r instanceof Date&&(r=
r.toUTCString()),m+="; "+p+"="+r}}if("auto"===q){for(var v=vf(),w=0;w<v.length;++w){var y="none"!=v[w]?v[w]:void 0;if(!wf(y,u)&&uf(m+(y?"; domain="+y:""),a,l)){k=!0;break a}}k=!1}else q&&"none"!=q&&(m+="; domain="+q),k=!wf(q,u)&&uf(m,a,l)}return k};function sf(a,b,c){for(var d=[],e=[],g,h=0;h<a.length;h++){var k=a[h],l=b(k);l===c?d.push(k):void 0===g||l<g?(e=[k],g=l):l===g&&e.push(k)}return 0<d.length?d:e}
function rf(a,b){for(var c=[],d=qf(a),e=0;e<d.length;e++){var g=d[e].split("."),h=g.shift();if(!b||-1!==b.indexOf(h)){var k=g.shift();k&&(k=k.split("-"),c.push({id:g.join("."),Lb:1*k[0]||1,lb:1*k[1]||1}))}}return c}
var yf=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,zf=/(^|\.)doubleclick\.net$/i,wf=function(a,b){return zf.test(document.location.hostname)||"/"===b&&yf.test(a)},vf=function(){var a=[],b=document.location.hostname.split(".");if(4===b.length){var c=b[b.length-1];if(parseInt(c,10).toString()===c)return["none"]}for(var d=b.length-2;0<=d;d--)a.push(b.slice(d).join("."));var e=document.location.hostname;zf.test(e)||yf.test(e)||a.push("none");return a};var Af="".split(/,/),Bf=!1;var Cf=null,Df={},Ef={},Gf,Hf=function(a,b){var c={event:a};b&&(c.eventModel=B(b),b[I.cc]&&(c.eventCallback=b[I.cc]),b[I.Ra]&&(c.eventTimeout=b[I.Ra]));return c};
var If=function(){Cf=Cf||!Ac.gtagRegistered;Ac.gtagRegistered=!0;return Cf},Jf=function(a){if(void 0===Ef[a.id]){var b;switch(a.prefix){case "UA":b=Re("gtagua",{trackingId:a.id});break;case "AW":b=Re("gtagaw",{conversionId:a});break;case "DC":b=Re("gtagfl",{targetId:a.id});break;case "GF":b=Re("gtaggf",{conversionId:a});break;case "G":b=Re("get",{trackingId:a.id,isAutoTag:!0});break;case "HA":b=Re("gtagha",{conversionId:a});break;case "GP":b=Re("gtaggp",{conversionId:a.id});break;default:return}if(!Gf){var c=
zb("v",{name:"send_to",dataLayerVersion:2});pb.push(c);Gf=["macro",pb.length-1]}var d={arg0:Gf,arg1:a.id,ignore_case:!1};d[Gb.la]="_lc";rb.push(d);var e={"if":[rb.length-1],add:[b]};e["if"]&&(e.add||e.block)&&qb.push(e);Ef[a.id]=b}},Kf=function(a){za(Df,function(b,c){var d=t(c,a);0<=d&&c.splice(d,1)})},Lf=Ha(function(){}),Mf=function(a){if(a.containerId!==zc.m&&"G"!==a.prefix){var b;switch(a.prefix){case "UA":b=14;break;case "AW":b=15;break;case "DC":b=16;break;default:b=17}J("GTM",b)}};
var Nf={config:function(a){var b=a[2]||{};if(2>a.length||!f(a[1])||!Pa(b))return;var c=wc(a[1]);if(!c)return;Kf(c.id);var d=c.id,e=b[I.ic]||"default";e=e.toString().split(",");for(var g=0;g<e.length;g++)Df[e[g]]=Df[e[g]]||[],Df[e[g]].push(d);delete b[I.ic];B(b);if(If()){if(Bf&&-1!==t(Af,c.prefix)){"G"===c.prefix&&(b[I.ka]=!0);kf(b,c.id);return}Jf(c);Mf(c)}else Lf();ud("gtag.targets."+c.id,void 0);ud("gtag.targets."+c.id,B(b));var h={};h[I.za]=c.id;return Hf(I.w,h);},
event:function(a){var b=a[1];if(f(b)&&!(3<a.length)){var c;if(2<a.length){if(!Pa(a[2])&&void 0!=a[2])return;c=a[2]}var d=Hf(b,c);var e;var g=c,h=od("gtag.fields.send_to",2);f(h)||(h=I.za);var k=g&&g[h];void 0===k&&(k=od(h,2),void 0===k&&(k="default"));if(f(k)||ua(k)){for(var l=k.toString().replace(/\s+/g,"").split(","),m=[],n=0;n<l.length;n++)0<=l[n].indexOf("-")?m.push(l[n]):m=m.concat(Df[l[n]]||[]);e=yc(m)}else e=void 0;var q=e;if(!q)return;var u=If();u||Lf();for(var p=
[],r=0;u&&r<q.length;r++){var v=q[r];Mf(v);if(Bf&&-1!==t(Af,v.prefix)){var w=B(c);"G"===v.prefix&&(w[I.ka]=!0);jf(b,w,v.id)}else Jf(v);p.push(v.id)}B(c,{event:b});d.eventModel=d.eventModel||{};0<q.length?d.eventModel[I.za]=p.join():delete d.eventModel[I.za];return d}},js:function(a){if(2==a.length&&a[1].getTime)return{event:"gtm.js","gtm.start":a[1].getTime()}},policy:function(a){3===a.length&&(void 0).Fh().yh(a[1],a[2])},set:function(a){var b;2==a.length&&Pa(a[1])?b=
B(a[1]):3==a.length&&f(a[1])&&(b={},Pa(a[2])||ua(a[2])?b[a[1]]=B(a[2]):b[a[1]]=a[2]);if(b){if(If()){var c=B(b);ff().push("set",[c])}B(b);b._clear=!0;return b}}},Of={policy:!0};var Qf=function(a){return Pf?F.querySelectorAll(a):null},Rf=function(a,b){if(!Pf)return null;if(Element.prototype.closest)try{return a.closest(b)}catch(e){return null}var c=Element.prototype.matches||Element.prototype.webkitMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.msMatchesSelector||Element.prototype.oMatchesSelector,d=a;if(!F.documentElement.contains(d))return null;do{try{if(c.call(d,b))return d}catch(e){break}d=d.parentElement||d.parentNode}while(null!==d&&1===d.nodeType);
return null},Sf=!1;if(F.querySelectorAll)try{var Tf=F.querySelectorAll(":root");Tf&&1==Tf.length&&Tf[0]==F.documentElement&&(Sf=!0)}catch(a){}var Pf=Sf;var $f=function(a){if(Zf(a))return a;this.nh=a};$f.prototype.ig=function(){return this.nh};var Zf=function(a){return!a||"object"!==Na(a)||Pa(a)?!1:"getUntrustedUpdateValue"in a};$f.prototype.getUntrustedUpdateValue=$f.prototype.ig;var ag=!1,bg=[];function cg(){if(!ag){ag=!0;for(var a=0;a<bg.length;a++)G(bg[a])}}var dg=function(a){ag?G(a):bg.push(a)};var eg=[],fg=!1,gg=function(a){return D["dataLayer"].push(a)},hg=function(a){var b=Ac["dataLayer"],c=b?b.subscribers:1,d=0;return function(){++d===c&&a()}},jg=function(a){var b=a._clear;za(a,function(g,h){"_clear"!==g&&(b&&ud(g,void 0),ud(g,h))});Fc||(Fc=a["gtm.start"]);var c=a.event;if(!c)return!1;var d=a["gtm.uniqueEventId"];d||(d=Lc(),a["gtm.uniqueEventId"]=d,ud("gtm.uniqueEventId",d));Hc=c;var e=ig(a);
Hc=null;switch(c){case "gtm.init":J("GTM",19),e&&J("GTM",20)}return e};function ig(a){var b=a.event,c=a["gtm.uniqueEventId"],d,e=Ac.zones;d=e?e.checkState(zc.m,c):Ud;return d.active?Qe(c,b,d.isWhitelisted,a.eventCallback,a.eventTimeout)?!0:!1:!1}
var kg=function(){for(var a=!1;!fg&&0<eg.length;){fg=!0;delete ld.eventModel;nd();var b=eg.shift();if(null!=b){var c=Zf(b);if(c){var d=b;b=Zf(d)?d.getUntrustedUpdateValue():void 0;for(var e=["gtm.whitelist","gtm.blacklist","tagTypeBlacklist"],g=0;g<e.length;g++){var h=e[g],k=od(h,1);if(ua(k)||Pa(k))k=B(k);md[h]=k}}try{if(qa(b))try{b.call(pd)}catch(v){}else if(ua(b)){var l=b;if(f(l[0])){var m=
l[0].split("."),n=m.pop(),q=l.slice(1),u=od(m.join("."),2);if(void 0!==u&&null!==u)try{u[n].apply(u,q)}catch(v){}}}else{var p=b;if(p&&("[object Arguments]"==Object.prototype.toString.call(p)||Object.prototype.hasOwnProperty.call(p,"callee"))){a:{if(b.length&&f(b[0])){var r=Nf[b[0]];if(r&&(!c||!Of[b[0]])){b=r(b);break a}}b=void 0}if(!b){fg=!1;continue}}a=jg(b)||a}}finally{c&&nd(!0)}}fg=!1}
return!a},lg=function(){var a=kg();try{var b=zc.m,c=D["dataLayer"].hide;if(c&&void 0!==c[b]&&c.end){c[b]=!1;var d=!0,e;for(e in c)if(c.hasOwnProperty(e)&&!0===c[e]){d=!1;break}d&&(c.end(),c.end=null)}}catch(g){}return a},ng=function(){var a=Ub("dataLayer",[]),b=Ub("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};ae(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});dg(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});b.subscribers=(b.subscribers||
0)+1;var c=a.push;a.push=function(){var d;if(0<Ac.SANDBOXED_JS_SEMAPHORE){d=[];for(var e=0;e<arguments.length;e++)d[e]=new $f(arguments[e])}else d=[].slice.call(arguments,0);var g=c.apply(a,d);eg.push.apply(eg,d);if(300<this.length)for(J("GTM",4);300<this.length;)this.shift();var h="boolean"!==typeof g||g;return kg()&&h};eg.push.apply(eg,a.slice(0));mg()&&G(lg)},mg=function(){var a=!0;return a};var og;var Kg={};Kg.yb=new String("undefined");
var Lg=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===Kg.yb?b:a[d]);return c.join("")}};Lg.prototype.toString=function(){return this.resolve("undefined")};Lg.prototype.valueOf=Lg.prototype.toString;Kg.kf=Lg;Kg.sc={};Kg.Uf=function(a){return new Lg(a)};var Mg={};Kg.Yg=function(a,b){var c=Lc();Mg[c]=[a,b];return c};Kg.Qd=function(a){var b=a?0:1;return function(c){var d=Mg[c];if(d&&"function"===typeof d[b])d[b]();Mg[c]=void 0}};Kg.Bg=function(a){for(var b=!1,c=!1,
d=2;d<a.length;d++)b=b||8===a[d],c=c||16===a[d];return b&&c};Kg.Mg=function(a){if(a===Kg.yb)return a;var b=Lc();Kg.sc[b]=a;return'google_tag_manager["'+zc.m+'"].macro('+b+")"};Kg.Fg=function(a,b,c){a instanceof Kg.kf&&(a=a.resolve(Kg.Yg(b,c)),b=pa);return{Ec:a,s:b}};var Ng=function(a,b,c){function d(g,h){var k=g[h];return k}var e={event:b,"gtm.element":a,"gtm.elementClasses":d(a,"className"),"gtm.elementId":a["for"]||bc(a,"id")||"","gtm.elementTarget":a.formTarget||d(a,"target")||""};c&&(e["gtm.triggers"]=c.join(","));e["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||d(a,"href")||a.src||a.code||a.codebase||
"";return e},Og=function(a){Ac.hasOwnProperty("autoEventsSettings")||(Ac.autoEventsSettings={});var b=Ac.autoEventsSettings;b.hasOwnProperty(a)||(b[a]={});return b[a]},Pg=function(a,b,c){Og(a)[b]=c},Qg=function(a,b,c,d){var e=Og(a),g=Ga(e,b,d);e[b]=c(g)},Rg=function(a,b,c){var d=Og(a);return Ga(d,b,c)};var Sg=function(){for(var a=Sb.userAgent+(F.cookie||"")+(F.referrer||""),b=a.length,c=D.history.length;0<c;)a+=c--^b++;var d=1,e,g,h;if(a)for(d=0,g=a.length-1;0<=g;g--)h=a.charCodeAt(g),d=(d<<6&268435455)+h+(h<<14),e=d&266338304,d=0!=e?d^e>>21:d;return[Math.round(2147483647*Math.random())^d&2147483647,Math.round(Fa()/1E3)].join(".")},Vg=function(a,b,c,d){var e=Tg(b);return tf(a,e,Ug(c),d)},Wg=function(a,b,c,d){var e=""+Tg(c),g=Ug(d);1<g&&(e+="-"+g);return[b,e,a].join(".")},Tg=function(a){if(!a)return 1;
a=0===a.indexOf(".")?a.substr(1):a;return a.split(".").length},Ug=function(a){if(!a||"/"===a)return 1;"/"!==a[0]&&(a="/"+a);"/"!==a[a.length-1]&&(a+="/");return a.split("/").length-1};var Xg=["1"],Yg={},bh=function(a,b,c,d){var e=Zg(a);Yg[e]||$g(e,b,c)||(ah(e,Sg(),b,c,d),$g(e,b,c))};function ah(a,b,c,d,e){var g=Wg(b,"1",d,c);xf(a,g,c,d,0==e?void 0:new Date(Fa()+1E3*(void 0==e?7776E3:e)))}function $g(a,b,c){var d=Vg(a,b,c,Xg);d&&(Yg[a]=d);return d}function Zg(a){return(a||"_gcl")+"_au"};var ch=function(){for(var a=[],b=F.cookie.split(";"),c=/^\s*_gac_(UA-\d+-\d+)=\s*(.+?)\s*$/,d=0;d<b.length;d++){var e=b[d].match(c);e&&a.push({ad:e[1],value:e[2]})}var g={};if(!a||!a.length)return g;for(var h=0;h<a.length;h++){var k=a[h].value.split(".");"1"==k[0]&&3==k.length&&k[1]&&(g[a[h].ad]||(g[a[h].ad]=[]),g[a[h].ad].push({timestamp:k[1],fg:k[2]}))}return g};function dh(){for(var a=eh,b={},c=0;c<a.length;++c)b[a[c]]=c;return b}function fh(){var a="ABCDEFGHIJKLMNOPQRSTUVWXYZ";a+=a.toLowerCase()+"0123456789-_";return a+"."}
var eh,gh,hh=function(a){eh=eh||fh();gh=gh||dh();for(var b=[],c=0;c<a.length;c+=3){var d=c+1<a.length,e=c+2<a.length,g=a.charCodeAt(c),h=d?a.charCodeAt(c+1):0,k=e?a.charCodeAt(c+2):0,l=g>>2,m=(g&3)<<4|h>>4,n=(h&15)<<2|k>>6,q=k&63;e||(q=64,d||(n=64));b.push(eh[l],eh[m],eh[n],eh[q])}return b.join("")},ih=function(a){function b(l){for(;d<a.length;){var m=a.charAt(d++),n=gh[m];if(null!=n)return n;if(!/^[\s\xa0]*$/.test(m))throw Error("Unknown base64 encoding at char: "+m);}return l}eh=eh||fh();gh=gh||
dh();for(var c="",d=0;;){var e=b(-1),g=b(0),h=b(64),k=b(64);if(64===k&&-1===e)return c;c+=String.fromCharCode(e<<2|g>>4);64!=h&&(c+=String.fromCharCode(g<<4&240|h>>2),64!=k&&(c+=String.fromCharCode(h<<6&192|k)))}};var jh;function kh(a,b){if(!a||b===F.location.hostname)return!1;for(var c=0;c<a.length;c++)if(a[c]instanceof RegExp){if(a[c].test(b))return!0}else if(0<=b.indexOf(a[c]))return!0;return!1}
var oh=function(){var a=lh,b=mh,c=nh(),d=function(h){a(h.target||h.srcElement||{})},e=function(h){b(h.target||h.srcElement||{})};if(!c.init){$b(F,"mousedown",d);$b(F,"keyup",d);$b(F,"submit",e);var g=HTMLFormElement.prototype.submit;HTMLFormElement.prototype.submit=function(){b(this);g.call(this)};c.init=!0}},nh=function(){var a=Ub("google_tag_data",{}),b=a.gl;b&&b.decorators||(b={decorators:[]},a.gl=b);return b};var ph=/(.*?)\*(.*?)\*(.*)/,qh=/^https?:\/\/([^\/]*?)\.?cdn\.ampproject\.org\/?(.*)/,rh=/^(?:www\.|m\.|amp\.)+/,sh=/([^?#]+)(\?[^#]*)?(#.*)?/,th=/(.*?)(^|&)_gl=([^&]*)&?(.*)/,vh=function(a){var b=[],c;for(c in a)if(a.hasOwnProperty(c)){var d=a[c];void 0!==d&&d===d&&null!==d&&"[object Object]"!==d.toString()&&(b.push(c),b.push(hh(String(d))))}var e=b.join("*");return["1",uh(e),e].join("*")},uh=function(a,b){var c=[window.navigator.userAgent,(new Date).getTimezoneOffset(),window.navigator.userLanguage||
window.navigator.language,Math.floor((new Date).getTime()/60/1E3)-(void 0===b?0:b),a].join("*"),d;if(!(d=jh)){for(var e=Array(256),g=0;256>g;g++){for(var h=g,k=0;8>k;k++)h=h&1?h>>>1^3988292384:h>>>1;e[g]=h}d=e}jh=d;for(var l=4294967295,m=0;m<c.length;m++)l=l>>>8^jh[(l^c.charCodeAt(m))&255];return((l^-1)>>>0).toString(36)},xh=function(){return function(a){var b=Be(D.location.href),c=b.search.replace("?",""),d=xe(c,"_gl",!0)||"";a.query=wh(d)||{};var e=Ae(b,"fragment").match(th);a.fragment=wh(e&&e[3]||
"")||{}}},yh=function(){var a=xh(),b=nh();b.data||(b.data={query:{},fragment:{}},a(b.data));var c={},d=b.data;d&&(Ia(c,d.query),Ia(c,d.fragment));return c},wh=function(a){var b;b=void 0===b?3:b;try{if(a){var c;a:{for(var d=a,e=0;3>e;++e){var g=ph.exec(d);if(g){c=g;break a}d=decodeURIComponent(d)}c=void 0}var h=c;if(h&&"1"===h[1]){var k=h[3],l;a:{for(var m=h[2],n=0;n<b;++n)if(m===uh(k,n)){l=!0;break a}l=!1}if(l){for(var q={},u=k?k.split("*"):[],p=0;p<u.length;p+=2)q[u[p]]=ih(u[p+1]);return q}}}}catch(r){}};
function zh(a,b,c){function d(m){var n=m,q=th.exec(n),u=n;if(q){var p=q[2],r=q[4];u=q[1];r&&(u=u+p+r)}m=u;var v=m.charAt(m.length-1);m&&"&"!==v&&(m+="&");return m+l}c=void 0===c?!1:c;var e=sh.exec(b);if(!e)return"";var g=e[1],h=e[2]||"",k=e[3]||"",l="_gl="+a;c?k="#"+d(k.substring(1)):h="?"+d(h.substring(1));return""+g+h+k}
function Ah(a,b,c){for(var d={},e={},g=nh().decorators,h=0;h<g.length;++h){var k=g[h];(!c||k.forms)&&kh(k.domains,b)&&(k.fragment?Ia(e,k.callback()):Ia(d,k.callback()))}if(Ja(d)){var l=vh(d);if(c){if(a&&a.action){var m=(a.method||"").toLowerCase();if("get"===m){for(var n=a.childNodes||[],q=!1,u=0;u<n.length;u++){var p=n[u];if("_gl"===p.name){p.setAttribute("value",l);q=!0;break}}if(!q){var r=F.createElement("input");r.setAttribute("type","hidden");r.setAttribute("name","_gl");r.setAttribute("value",
l);a.appendChild(r)}}else if("post"===m){var v=zh(l,a.action);ve.test(v)&&(a.action=v)}}}else Bh(l,a,!1)}if(!c&&Ja(e)){var w=vh(e);Bh(w,a,!0)}}function Bh(a,b,c){if(b.href){var d=zh(a,b.href,void 0===c?!1:c);ve.test(d)&&(b.href=d)}}
var lh=function(a){try{var b;a:{for(var c=a,d=100;c&&0<d;){if(c.href&&c.nodeName.match(/^a(?:rea)?$/i)){b=c;break a}c=c.parentNode;d--}b=null}var e=b;if(e){var g=e.protocol;"http:"!==g&&"https:"!==g||Ah(e,e.hostname,!1)}}catch(h){}},mh=function(a){try{if(a.action){var b=Ae(Be(a.action),"host");Ah(a,b,!0)}}catch(c){}},Ch=function(a,b,c,d){oh();var e={callback:a,domains:b,fragment:"fragment"===c,forms:!!d};nh().decorators.push(e)},Dh=function(){var a=F.location.hostname,b=qh.exec(F.referrer);if(!b)return!1;
var c=b[2],d=b[1],e="";if(c){var g=c.split("/"),h=g[1];e="s"===h?decodeURIComponent(g[2]):decodeURIComponent(h)}else if(d){if(0===d.indexOf("xn--"))return!1;e=d.replace(/-/g,".").replace(/\.\./g,"-")}var k=a.replace(rh,""),l=e.replace(rh,""),m;if(!(m=k===l)){var n="."+l;m=k.substring(k.length-n.length,k.length)===n}return m},Eh=function(a,b){return!1===a?!1:a||b||Dh()};var Fh={};var Gh=/^\w+$/,Hh=/^[\w-]+$/,Ih=/^~?[\w-]+$/,Jh={aw:"_aw",dc:"_dc",gf:"_gf",ha:"_ha",gp:"_gp"};function Kh(a){return a&&"string"==typeof a&&a.match(Gh)?a:"_gcl"}var Mh=function(){var a=Be(D.location.href),b=Ae(a,"query",!1,void 0,"gclid"),c=Ae(a,"query",!1,void 0,"gclsrc"),d=Ae(a,"query",!1,void 0,"dclid");if(!b||!c){var e=a.hash.replace("#","");b=b||xe(e,"gclid",void 0);c=c||xe(e,"gclsrc",void 0)}return Lh(b,c,d)};
function Lh(a,b,c){var d={},e=function(g,h){d[h]||(d[h]=[]);d[h].push(g)};if(void 0!==a&&a.match(Hh))switch(b){case void 0:e(a,"aw");break;case "aw.ds":e(a,"aw");e(a,"dc");break;case "ds":e(a,"dc");break;case "3p.ds":(void 0==Fh.gtm_3pds?0:Fh.gtm_3pds)&&e(a,"dc");break;case "gf":e(a,"gf");break;case "ha":e(a,"ha");break;case "gp":e(a,"gp")}c&&e(c,"dc");return d}var Oh=function(a){var b=Mh();Nh(b,a)};
function Nh(a,b,c){function d(q,u){var p=Ph(q,e);p&&xf(p,u,h,g,l,!0)}b=b||{};var e=Kh(b.prefix),g=b.domain||"auto",h=b.path||"/",k=void 0==b.Ia?7776E3:b.Ia;c=c||Fa();var l=0==k?void 0:new Date(c+1E3*k),m=Math.round(c/1E3),n=function(q){return["GCL",m,q].join(".")};a.aw&&(!0===b.Th?d("aw",n("~"+a.aw[0])):d("aw",n(a.aw[0])));a.dc&&d("dc",n(a.dc[0]));a.gf&&d("gf",n(a.gf[0]));a.ha&&d("ha",n(a.ha[0]));a.gp&&d("gp",n(a.gp[0]))}
var Rh=function(a,b,c,d,e){for(var g=yh(),h=Kh(b),k=0;k<a.length;++k){var l=a[k];if(void 0!==Jh[l]){var m=Ph(l,h),n=g[m];if(n){var q=Math.min(Qh(n),Fa()),u;b:{for(var p=q,r=qf(m,F.cookie),v=0;v<r.length;++v)if(Qh(r[v])>p){u=!0;break b}u=!1}u||xf(m,n,c,d,0==e?void 0:new Date(q+1E3*(null==e?7776E3:e)),!0)}}}var w={prefix:b,path:c,domain:d};Nh(Lh(g.gclid,g.gclsrc),w)},Ph=function(a,b){var c=Jh[a];if(void 0!==c)return b+c},Qh=function(a){var b=a.split(".");return 3!==b.length||"GCL"!==b[0]?0:1E3*(Number(b[1])||
0)};function Sh(a){var b=a.split(".");if(3==b.length&&"GCL"==b[0]&&b[1])return b[2]}
var Th=function(a,b,c,d,e){if(ua(b)){var g=Kh(e);Ch(function(){for(var h={},k=0;k<a.length;++k){var l=Ph(a[k],g);if(l){var m=qf(l,F.cookie);m.length&&(h[l]=m.sort()[m.length-1])}}return h},b,c,d)}},Uh=function(a){return a.filter(function(b){return Ih.test(b)})},Vh=function(a,b){for(var c=Kh(b&&b.prefix),d={},e=0;e<a.length;e++)Jh[a[e]]&&(d[a[e]]=Jh[a[e]]);za(d,function(g,h){var k=qf(c+h,F.cookie);if(k.length){var l=k[0],m=Qh(l),n={};n[g]=[Sh(l)];Nh(n,b,m)}})};var Wh=/^\d+\.fls\.doubleclick\.net$/;function Xh(a){var b=Be(D.location.href),c=Ae(b,"host",!1);if(c&&c.match(Wh)){var d=Ae(b,"path").split(a+"=");if(1<d.length)return d[1].split(";")[0].split("?")[0]}}
function Yh(a,b){if("aw"==a||"dc"==a){var c=Xh("gcl"+a);if(c)return c.split(".")}var d=Kh(b);if("_gcl"==d){var e;e=Mh()[a]||[];if(0<e.length)return e}var g=Ph(a,d),h;if(g){var k=[];if(F.cookie){var l=qf(g,F.cookie);if(l&&0!=l.length){for(var m=0;m<l.length;m++){var n=Sh(l[m]);n&&-1===t(k,n)&&k.push(n)}h=Uh(k)}else h=k}else h=k}else h=[];return h}
var Zh=function(){var a=Xh("gac");if(a)return decodeURIComponent(a);var b=ch(),c=[];za(b,function(d,e){for(var g=[],h=0;h<e.length;h++)g.push(e[h].fg);g=Uh(g);g.length&&c.push(d+":"+g.join(","))});return c.join(";")},$h=function(a,b,c,d,e){bh(b,c,d,e);var g=Yg[Zg(b)],h=Mh().dc||[],k=!1;if(g&&0<h.length){var l=Ac.joined_au=Ac.joined_au||{},m=b||"_gcl";if(!l[m])for(var n=0;n<h.length;n++){var q="http://ad.doubleclick.net/ddm/regclk",u=q=q+"?gclid="+h[n]+"&auiddc="+g;Sb.sendBeacon&&Sb.sendBeacon(u)||Zb(u);k=l[m]=
!0}}null==a&&(a=k);if(a&&g){var p=Zg(b),r=Yg[p];r&&ah(p,r,c,d,e)}};var ai;if(3===zc.Cb.length)ai="g";else{var bi="G";bi="g";ai=bi}
var ci={"":"n",UA:"u",AW:"a",DC:"d",G:"e",GF:"f",HA:"h",GTM:ai,OPT:"o"},di=function(a){var b=zc.m.split("-"),c=b[0].toUpperCase(),d=ci[c]||"i",e=a&&"GTM"===c?b[1]:"OPT"===c?b[1]:"",g;if(3===zc.Cb.length){var h=void 0;h=h||(xd()?"s":"o");g="2"+(h||"w")}else g=
"";return g+d+zc.Cb+e};
var ei=function(a){return!(void 0===a||null===a||0===(a+"").length)},fi=function(a,b){var c;if(2===b.S)return a("ord",wa(1E11,1E13)),!0;if(3===b.S)return a("ord","1"),a("num",wa(1E11,1E13)),!0;if(4===b.S)return ei(b.sessionId)&&a("ord",b.sessionId),!0;if(5===b.S)c="1";else if(6===b.S)c=b.Vc;else return!1;ei(c)&&a("qty",c);ei(b.Ib)&&a("cost",b.Ib);ei(b.transactionId)&&a("ord",b.transactionId);return!0},gi=encodeURIComponent,hi=function(a,b){function c(n,q,u){g.hasOwnProperty(n)||(q+="",e+=";"+n+"="+
(u?q:gi(q)))}var d=a.Bc,e=a.protocol;e+=a.Tb?"//"+d+".fls.doubleclick.net/activityi":"//ad.doubleclick.net/activity";e+=";src="+gi(d)+(";type="+gi(a.Dc))+(";cat="+gi(a.eb));var g=a.Wf||{};za(g,function(n,q){e+=";"+gi(n)+"="+gi(q+"")});if(fi(c,a)){ei(a.$b)&&c("u",a.$b);ei(a.Zb)&&c("tran",a.Zb);c("gtm",di());!1===a.wf&&c("npa","1");if(a.zc){var h=Yh("dc",a.Da);h&&h.length&&c("gcldc",h.join("."));var k=Yh("aw",a.Da);k&&k.length&&c("gclaw",k.join("."));var l=Zh();l&&c("gac",l);bh(a.Da,void 0,a.Sf,a.Tf);
var m=Yg[Zg(a.Da)];m&&c("auiddc",m)}ei(a.Rc)&&c("prd",a.Rc,!0);za(a.cd,function(n,q){c(n,q)});e+=b||"";ei(a.Rb)&&c("~oref",a.Rb);a.Tb?Yb(e+"?",a.s):Zb(e+"?",a.s,a.o)}else G(a.o)};var ii=["input","select","textarea"],ji=["button","hidden","image","reset","submit"],ki=function(a){var b=a.tagName.toLowerCase();return!va(ii,function(c){return c===b})||"input"===b&&va(ji,function(c){return c===a.type.toLowerCase()})?!1:!0},li=function(a){return a.form?a.form.tagName?a.form:F.getElementById(a.form):ec(a,["form"],100)},mi=function(a,b,c){if(!a.elements)return 0;for(var d=b.getAttribute(c),e=0,g=1;e<a.elements.length;e++){var h=a.elements[e];if(ki(h)){if(h.getAttribute(c)===d)return g;
g++}}return 0};
var pi=function(a){var b;if(a.hasOwnProperty("conversion_data"))b="conversion_data";else if(a.hasOwnProperty("price"))b="price";else return;var c=b,d="/pagead/conversion/"+ni(a.conversion_id)+"/?",e=ni(JSON.stringify(a[c])),g="https://www.googletraveladservices.com/travel/flights/clk"+d+c+"="+e;if(a.conversionLinkerEnabled){var h=Yh("gf",a.cookiePrefix);if(h&&h.length)for(var k=0;k<h.length;k++)g+="&gclgf="+ni(h[k])}Zb(g,a.onSuccess,a.onFailure)},ni=function(a){return null===a||void 0===a||0===String(a).length?
"":encodeURIComponent(String(a))};var qi=!!D.MutationObserver,ri=void 0,si=function(a){if(!ri){var b=function(){var c=F.body;if(c)if(qi)(new MutationObserver(function(){for(var e=0;e<ri.length;e++)G(ri[e])})).observe(c,{childList:!0,subtree:!0});else{var d=!1;$b(c,"DOMNodeInserted",function(){d||(d=!0,G(function(){d=!1;for(var e=0;e<ri.length;e++)G(ri[e])}))})}};ri=[];F.body?b():G(b)}ri.push(a)};var Ui=D.clearTimeout,Vi=D.setTimeout,R=function(a,b,c){if(xd()){b&&G(b)}else return Wb(a,b,c)},Wi=function(){return D.location.href},Xi=function(a){return Ae(Be(a),"fragment")},Yi=function(a){return ze(Be(a))},V=function(a,b){return od(a,b||2)},Zi=function(a,b,c){b&&(a.eventCallback=b,c&&(a.eventTimeout=c));return gg(a)},$i=function(a,b){D[a]=b},W=function(a,b,c){b&&(void 0===D[a]||c&&!D[a])&&(D[a]=b);return D[a]},
aj=function(a,b,c){return qf(a,b,void 0===c?!0:!!c)},bj=function(a,b){if(xd()){b&&G(b)}else Yb(a,b)},cj=function(a){return!!Rg(a,"init",!1)},dj=function(a){Pg(a,"init",!0)},ej=function(a,b,c){var d=(void 0===c?0:c)?"www.googletagmanager.com/gtag/js":Ec;d+="?id="+encodeURIComponent(a)+"&l=dataLayer";b&&za(b,function(e,g){g&&(d+="&"+e+"="+encodeURIComponent(g))});R(P("https://","http://",d))},fj=function(a,b){var c=a[b];return c};
var gj=Kg.Fg;var hj=new xa,ij=function(a,b){function c(h){var k=Be(h),l=Ae(k,"protocol"),m=Ae(k,"host",!0),n=Ae(k,"port"),q=Ae(k,"path").toLowerCase().replace(/\/$/,"");if(void 0===l||"http"==l&&"80"==n||"https"==l&&"443"==n)l="web",n="default";return[l,m,n,q]}for(var d=c(String(a)),e=c(String(b)),g=0;g<d.length;g++)if(d[g]!==e[g])return!1;return!0},kj=function(a){return jj(a)?1:0};
function jj(a){var b=a.arg0,c=a.arg1;if(a.any_of&&ua(c)){for(var d=0;d<c.length;d++)if(kj({"function":a["function"],arg0:b,arg1:c[d]}))return!0;return!1}switch(a["function"]){case "_cn":return 0<=String(b).indexOf(String(c));case "_css":var e;a:{if(b){var g=["matches","webkitMatchesSelector","mozMatchesSelector","msMatchesSelector","oMatchesSelector"];try{for(var h=0;h<g.length;h++)if(b[g[h]]){e=b[g[h]](c);break a}}catch(v){}}e=!1}return e;case "_ew":var k,l;k=String(b);l=String(c);var m=k.length-
l.length;return 0<=m&&k.indexOf(l,m)==m;case "_eq":return String(b)==String(c);case "_ge":return Number(b)>=Number(c);case "_gt":return Number(b)>Number(c);case "_lc":var n;n=String(b).split(",");return 0<=t(n,String(c));case "_le":return Number(b)<=Number(c);case "_lt":return Number(b)<Number(c);case "_re":var q;var u=a.ignore_case?"i":void 0;try{var p=String(c)+u,r=hj.get(p);r||(r=new RegExp(c,u),hj.set(p,r));q=r.test(b)}catch(v){q=!1}return q;case "_sw":return 0==String(b).indexOf(String(c));case "_um":return ij(b,
c)}return!1};var mj=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var nj={},oj=encodeURI,X=encodeURIComponent,pj=Zb;var qj=function(a,b){if(!a)return!1;var c=Ae(Be(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var g=c.length-e.length;0<g&&"."!=e.charAt(0)&&(g--,e="."+e);if(0<=g&&c.indexOf(e,g)==g)return!0}}return!1};
var rj=function(a,b,c){for(var d={},e=!1,g=0;a&&g<a.length;g++)a[g]&&a[g].hasOwnProperty(b)&&a[g].hasOwnProperty(c)&&(d[a[g][b]]=a[g][c],e=!0);return e?d:null};nj.Cg=function(){var a=!1;return a};var xk=function(){var a=D.gaGlobal=D.gaGlobal||{};a.hid=a.hid||wa();return a.hid};var Ik=window,Jk=document,Kk=function(a){var b=Ik._gaUserPrefs;if(b&&b.ioo&&b.ioo()||a&&!0===Ik["ga-disable-"+a])return!0;try{var c=Ik.external;if(c&&c._gaUserPrefs&&"oo"==c._gaUserPrefs)return!0}catch(g){}for(var d=qf("AMP_TOKEN",Jk.cookie,!0),e=0;e<d.length;e++)if("$OPT_OUT"==d[e])return!0;return Jk.getElementById("__gaOptOutExtension")?!0:!1};
var Nk=function(a){return"_"===a.charAt(0)},Ok=function(a){za(a,function(c){Nk(c)&&delete a[c]});var b=a[I.V]||{};za(b,function(c){Nk(c)&&delete b[c]})};var Rk=function(a,b,c){jf(b,c,a)},Sk=function(a,b,c){jf(b,c,a,!0)},Uk=function(a,b){},Tk=function(a,b){};

var Vk=!1,Wk=[],Xk=["aw","dc"],Yk=function(a){var b=D.google_trackConversion,c=a.gtm_onFailure;"function"==typeof b?b(a)||c():c()},Zk=function(){for(;0<Wk.length;)Yk(Wk.shift())},$k=function(a){if(!Vk){Vk=!0;je();var b=function(){Zk();Wk={push:Yk}};xd()?b():Wb(a,b,function(){Zk();Vk=!1})}},al=function(a){if(a){for(var b=[],c=0;c<a.length;++c){var d=a[c];d&&b.push({item_id:d.id,quantity:d.quantity,value:d.price,start_date:d.start_date,end_date:d.end_date})}return b}},bl=function(a,b,c,d){var e=wc(a),
g=b==I.w,h=e.h[0],k=e.h[1],l=void 0!==k,m=function(H){return d.getWithConfig(H)},n=!1!==m(I.wa),q=m(I.va)||m(I.P),u=m(I.T),p=m(I.U),r=-1==navigator.userAgent.toLowerCase().indexOf("firefox")?P("https://","http://","www.googleadservices.com/pagead/conversion_async.js"):"https://www.google.com/pagead/conversion_async.js";if(g){var v=m(I.ja)||{};if(n){Eh(v[I.Sa],!!v[I.F])&&Rh(Xk,q,void 0,u,p);var w={prefix:q,domain:u,Ia:p};Oh(w);Vh(["aw","dc"],w)}v[I.F]&&Th(Xk,v[I.F],v[I.Ua],!!v[I.Ta],q);Kd(e)}var y=
!1===m(I.od)||!1===m(I.Xa);if(!g||!l&&!y)if(!0===m(I.pd)&&(l=!1),!1!==m(I.O)||l){var x={google_conversion_id:h,google_remarketing_only:!l,onload_callback:d.s,gtm_onFailure:d.o,google_conversion_format:"3",google_conversion_color:"ffffff",google_conversion_domain:"",google_conversion_label:k,google_conversion_language:m(I.ya),google_conversion_value:m(I.Z),google_conversion_currency:m(I.ca),google_conversion_order_id:m(I.Ya),google_user_id:m(I.$a),google_conversion_page_url:m(I.Va),google_conversion_referrer_url:m(I.Wa),
google_gtm:di()};xd()&&(x.opt_image_generator=function(){return new Image},x.google_enable_display_cookie_match=!1);!1===m(I.O)&&(x.google_allow_ad_personalization_signals=!1);x.google_read_gcl_cookie_opt_out=!n;n&&q&&(x.google_gcl_cookie_prefix=q);var z=function(){var H=m(I.Qa),K={event:b};if(ua(H)){J("GTM",26);for(var Q=0;Q<H.length;++Q){var Z=H[Q],T=m(Z);void 0!==T&&(K[Z]=T)}return K}var ha=d.eventModel;if(!ha)return null;B(ha,K);for(var ca=0;ca<I.gd.length;++ca)delete K[I.gd[ca]];return K}();
z&&(x.google_custom_params=z);!l&&m(I.Y)&&(x.google_gtag_event_data={items:m(I.Y),value:m(I.Z)});if(l&&"purchase"==b){x.google_conversion_merchant_id=m(I.td);x.google_basket_feed_country=m(I.rd);x.google_basket_feed_language=m(I.sd);x.google_basket_discount=m(I.qd);x.google_basket_transaction_type=b;x.google_disable_merchant_reported_conversions=!0===m(I.vd);xd()&&(x.google_disable_merchant_reported_conversions=!0);var C=al(m(I.Y));C&&(x.google_conversion_items=C)}var A=function(H,K){void 0!=K&&""!==
K&&(x.google_additional_conversion_params=x.google_additional_conversion_params||{},x.google_additional_conversion_params[H]=K)};l&&("boolean"===typeof m(I.jc)&&A("vdnc",m(I.jc)),A("vdltv",m(I.ud)));var E=!0;E&&Wk.push(x)}$k(r)};
var cl=function(a,b,c,d,e,g){var h={config:a,gtm:di()};c&&(bh(d,void 0,e,g),h.auiddc=Yg[Zg(d)]);b&&(h.loadInsecure=b);void 0===D.__dc_ns_processor&&(D.__dc_ns_processor=[]);D.__dc_ns_processor.push(h);Wb((b?"http":"https")+"://www.googletagmanager.com/dclk/ns/v1.js")},dl=function(a,b,c){var d=/^u([1-9]\d?|100)$/,e=a(I.He)||{},g=td(b,c),h={},k={};if(Pa(e))for(var l in e)if(e.hasOwnProperty(l)&&d.test(l)){var m=e[l];f(m)&&(h[l]=m)}for(var n=0;n<g.length;n++){var q=g[n];d.test(q)&&(h[q]=q)}for(var u in h)h.hasOwnProperty(u)&&
(k[u]=a(h[u]));return k},el=function(a){function b(l,m,n){void 0!==n&&0!==(n+"").length&&d.push(l+m+":"+c(n+""))}var c=encodeURIComponent,d=[],e=a(I.Y)||[];if(ua(e))for(var g=0;g<e.length;g++){var h=e[g],k=g+1;b("i",k,h.id);b("p",k,h.price);b("q",k,h.quantity);b("c",k,a(I.Ge));b("l",k,a(I.ya))}return d.join("|")},fl=function(a){var b=/^DC-(\d+)(\/([\w-]+)\/([\w-]+)\+(\w+))?$/.exec(a);if(b){var c={standard:2,unique:3,per_session:4,transactions:5,items_sold:6,"":1}[(b[5]||"").toLowerCase()];if(c)return{containerId:"DC-"+
b[1],L:b[3]?a:"",qf:b[1],pf:b[3]||"",eb:b[4]||"",S:c}}},hl=function(a,b,c,d){var e=fl(a);if(e){var g=function(K){return d.getWithConfig(K)},h=!1!==g(I.wa),k=g(I.va)||g(I.P),l=g(I.T),m=g(I.U),n=g(I.Je),q=3===yd();if(b===I.w){var u=g(I.ja)||{},p=g(I.Pa),r=void 0===p?!0:!!p;if(h){if(Eh(u[I.Sa],!!u[I.F])){Rh(gl,k,void 0,l,m);}var v={prefix:k,domain:l,Ia:m};Oh(v);Vh(gl,v);$h(r,k,void 0,l,m)}if(u[I.F]){
Th(gl,u[I.F],u[I.Ua],!!u[I.Ta],k);}if(n&&n.exclusion_parameters&&n.engines)if(xd()){}else cl(n,q,h,k,l,m);G(d.s)}else{var w={},y=g(I.Ie);if(Pa(y))for(var x in y)if(y.hasOwnProperty(x)){var z=y[x];void 0!==z&&null!==z&&(w[x]=z)}var C="";if(5===e.S||6===e.S)C=el(g);var A=dl(g,e.containerId,e.L),E=!0===g(I.Ce);if(xd()&&E){
E=!1}var H={eb:e.eb,zc:h,Sf:l,Tf:m,Da:k,Ib:g(I.Z),S:e.S,Wf:w,Bc:e.qf,Dc:e.pf,o:d.o,s:d.s,Rb:ze(Be(D.location.href)),Rc:C,protocol:q?"http:":"https:",Vc:g(I.We),Tb:E,sessionId:g(I.wb),Zb:void 0,transactionId:g(I.Ya),$b:void 0,cd:A,wf:!1!==g(I.O)};hi(H)}}else G(d.o)},gl=["aw","dc"];
var il=/.*\.google\.com(:\d+)?\/booking\/flights.*/,kl=function(a,b,c,d){var e=function(w){return d.getWithConfig(w)},g=wc(a).h[0],h=!1!==e(I.wa),k=e(I.va)||e(I.P),l=e(I.T),m=e(I.U);if(b===I.w){if(h){var n={prefix:k,domain:l,Ia:m};Oh(n);Vh(["aw","dc"],n)}G(d.s)}else{var q={conversion_id:g,onFailure:d.o,onSuccess:d.s,conversionLinkerEnabled:h,cookiePrefix:k},u=il.test(D.location.href);if("purchase"!==b)G(d.o);else{var r={partner_id:g,trip_type:e(I.$e),total_price:e(I.Z),currency:e(I.ca),is_direct_booking:u,flight_segment:jl(e(I.Y))},v=e(I.yd);v&&"object"===typeof v&&(r.passengers_total=v.total,r.passengers_adult=v.adult,r.passengers_child=v.child,r.passengers_infant_in_seat=v.infant_in_seat,r.passengers_infant_in_lap=v.infant_in_lap);q.conversion_data=r;pi(q)}}},
jl=function(a){if(a){for(var b=[],c=0,d=0;d<a.length;++d){var e=a[d];!e||void 0!==e.category&&""!==e.category&&"FlightSegment"!==e.category||(b[c]={cabin:e.travel_class,fare_product:e.fare_product,booking_code:e.booking_code,flight_number:e.flight_number,origin:e.origin,destination:e.destination,departure_date:e.start_date},c++)}return b}};
var nl=function(a,b,c,d){var e=wc(a),g=!1!==d.getWithConfig(I.wa),h=d.getWithConfig(I.va)||d.getWithConfig(I.P),k=d.getWithConfig(I.T),l=d.getWithConfig(I.U);if(b===I.w){var m=d.getWithConfig(I.ja)||{};if(g){Eh(m[I.Sa],!!m[I.F])&&Rh(ll,h,void 0,k,l);var n={prefix:h,domain:k,Ia:l};Oh(n);Vh(["aw","dc"],n)}if(m[I.F]){Th(ll,m[I.F],m[I.Ua],!!m[I.Ta],h);}G(d.s)}else if("purchase"===b){var q=d.getWithConfig(I.Ya),u=d.getWithConfig(I.Z),
p=d.getWithConfig(I.ca),r=d.getWithConfig(I.Y),v={};if(f(q)||"number"===typeof q)v.mg=String(q);f(p)&&(v.pg=p);if(f(u)||"number"===typeof u)v.rg=v.lg=String(u);if(ua(r)&&0!==r.length){var w=r[0];if(Pa(w)){if(f(w.id)||"number"===typeof w.id)v.qg=String(w.id);f(w.start_date)&&(v.ng=w.start_date);f(w.end_date)&&(v.og=w.end_date)}}var y=e.h[0],x=d.s,z=d.o;/^\d+$/.test(y)?Zb(ml(y,v,g,h),x,z):G(z)}else G(d.o)},ml=function(a,b,c,d){var e=encodeURIComponent(a),g=encodeURIComponent(ol(b)),h="https://www.googletraveladservices.com/travel/clk/pagead/conversion/"+
e+"/?data="+g;c&&(h+=Yh("ha",d).map(function(k){return"&gclha="+encodeURIComponent(k)}).join(""));return h},ol=function(a){function b(d,e){void 0!==e&&c.push(d+"="+e)}var c=[];b("hct_base_price",a.lg);b("hct_booking_xref",a.mg);b("hct_checkin_date",a.ng);b("hct_checkout_date",a.og);b("hct_currency_code",a.pg);b("hct_partner_hotel_id",a.qg);b("hct_total_price",a.rg);return c.join(";")},ll=["ha"];
var Cl=function(a,b,c,d){var e="https://www.google-analytics.com/analytics.js",g=qe();if(qa(g)){var h="gtag_"+a.split("-").join("_"),k=function(y){var x=[].slice.call(arguments,0);x[0]=h+"."+x[0];g.apply(window,x)},l=function(){var y=function(A,E){for(var H=0;E&&H<E.length;H++)k(A,E[H])},x=tl(b,d);if(x){var z=x.action;if("impressions"===z)y("ec:addImpression",x.vg);else if("promo_click"===z||"promo_view"===z){var C=x.Sc;y("ec:addPromo",x.Sc);C&&0<C.length&&"promo_click"===z&&k("ec:setAction",z)}else y("ec:addProduct",
x.Ka),k("ec:setAction",z,x.cb)}},m=function(){if(xd()){}else{var y=d.getWithConfig(I.Te);y&&(k("require",y,{dataLayer:"dataLayer"}),k("require","render"))}},n=ul(a,h,b,d);vl(h,n.Ea)&&(g(function(){oe()&&oe().remove(h)}),wl[h]=!1);g("create",a,n.Ea);(function(){var y=d.getWithConfig("custom_map");g(function(){if(Pa(y)){var x=n.fa,z=oe().getByName(h),C;for(C in y)if(y.hasOwnProperty(C)&&/^(dimension|metric)\d+$/.test(C)&&void 0!=y[C]){var A=z.get(xl(y[C]));yl(x,C,A)}}})})();(function(y){if(y){var x={};if(Pa(y))for(var z in zl)zl.hasOwnProperty(z)&&Al(zl[z],z,y[z],x);k("require","linkid",x)}})(n.linkAttribution);
var u=n[I.ja];if(u&&u[I.F]){var p=u[I.Ua];re(h+".",u[I.F],void 0===p?!!u.use_anchor:"fragment"===p,!!u[I.Ta])}var r=function(y,x,z){z&&(x=""+x);n.fa[y]=x};b===I.ac?(m(),k("send","pageview",n.fa)):b===I.w?(m(),Kd(a),0!=n.sendPageView&&k("send","pageview",n.fa)):"screen_view"===b?k("send","screenview",n.fa):"timing_complete"===b?(r("timingCategory",n.eventCategory,!0),r("timingVar",n.name,!0),r("timingValue",Aa(n.value)),void 0!==n.eventLabel&&r("timingLabel",n.eventLabel,!0),k("send","timing",n.fa)):
"exception"===b?k("send","exception",n.fa):"optimize.callback"!==b&&(0<=t("view_item_list select_content view_item add_to_cart remove_from_cart begin_checkout set_checkout_option purchase refund view_promotion checkout_progress".split(" "),b)&&(k("require","ec","ec.js"),l()),r("eventCategory",n.eventCategory,!0),r("eventAction",n.eventAction||b,!0),void 0!==n.eventLabel&&r("eventLabel",n.eventLabel,!0),void 0!==n.value&&r("eventValue",Aa(n.value)),k("send","event",n.fa));if(!Bl){Bl=!0;je();var v=
d.o,w=function(){oe().loaded||v()};xd()?G(w):Wb(e,w,v)}}else G(d.o)},Bl,wl={},Dl={client_id:1,client_storage:"storage",cookie_name:1,cookie_domain:1,cookie_expires:1,cookie_path:1,cookie_update:1,sample_rate:1,site_speed_sample_rate:1,use_amp_client_id:1,store_gac:1,conversion_linker:"storeGac"},El={anonymize_ip:1,app_id:1,app_installer_id:1,app_name:1,app_version:1,campaign:{name:"campaignName",source:"campaignSource",medium:"campaignMedium",term:"campaignTerm",content:"campaignContent",id:"campaignId"},
currency:"currencyCode",description:"exDescription",fatal:"exFatal",language:1,non_interaction:1,page_hostname:"hostname",page_referrer:"referrer",page_path:"page",page_location:"location",page_title:"title",screen_name:1,transport_type:"transport",user_id:1},Fl={content_id:1,event_category:1,event_action:1,event_label:1,link_attribution:1,linker:1,method:1,name:1,send_page_view:1,value:1},zl={cookie_name:1,cookie_expires:"duration",levels:1},Gl={anonymize_ip:1,fatal:1,non_interaction:1,use_amp_client_id:1,
send_page_view:1,store_gac:1,conversion_linker:1},Al=function(a,b,c,d){if(void 0!==c)if(Gl[b]&&(c=Ca(c)),"anonymize_ip"!==b||c||(c=void 0),1===a)d[xl(b)]=c;else if(f(a))d[a]=c;else for(var e in a)a.hasOwnProperty(e)&&void 0!==c[e]&&(d[a[e]]=c[e])},xl=function(a){return a&&f(a)?a.replace(/(_[a-z])/g,function(b){return b[1].toUpperCase()}):a},Hl=function(a){var b="general";0<=t("add_payment_info add_to_cart add_to_wishlist begin_checkout checkout_progress purchase refund remove_from_cart set_checkout_option".split(" "),
a)?b="ecommerce":0<=t("generate_lead login search select_content share sign_up view_item view_item_list view_promotion view_search_results".split(" "),a)?b="engagement":"exception"===a&&(b="error");return b},yl=function(a,b,c){a.hasOwnProperty(b)||(a[b]=c)},Il=function(a){if(ua(a)){for(var b=[],c=0;c<a.length;c++){var d=a[c];if(void 0!=d){var e=d.id,g=d.variant;void 0!=e&&void 0!=g&&b.push(String(e)+"."+String(g))}}return 0<b.length?b.join("!"):void 0}},ul=function(a,b,c,d){var e=function(C){return d.getWithConfig(C)},
g={},h={},k={},l=Il(e(I.Pe));l&&yl(h,"exp",l);var m=e("custom_map");if(Pa(m))for(var n in m)if(m.hasOwnProperty(n)&&/^(dimension|metric)\d+$/.test(n)&&void 0!=m[n]){var q=e(String(m[n]));void 0!==q&&yl(h,n,q)}for(var u=td(a),p=0;p<u.length;++p){var r=u[p],v=e(r);Fl.hasOwnProperty(r)?Al(Fl[r],r,v,g):El.hasOwnProperty(r)?Al(El[r],r,v,h):Dl.hasOwnProperty(r)?Al(Dl[r],r,v,k):/^(dimension|metric|content_group)\d+$/.test(r)?Al(1,r,v,h):r===I.P&&0>t(u,I.tb)&&(k.cookieName=v+"_ga")}yl(k,"cookieDomain","auto");
yl(h,"forceSSL",!0);yl(g,"eventCategory",Hl(c));0<=t(["view_item","view_item_list","view_promotion","view_search_results"],c)&&yl(h,"nonInteraction",!0);"login"===c||"sign_up"===c||"share"===c?yl(g,"eventLabel",e(I.Se)):"search"===c||"view_search_results"===c?yl(g,"eventLabel",e(I.Ye)):"select_content"===c&&yl(g,"eventLabel",e(I.Fe));var w=g[I.ja]||{},y=w[I.Sa];y||0!=y&&w[I.F]?k.allowLinker=!0:!1===y&&yl(k,"useAmpClientId",!1);if(!1===e(I.De)||!1===e(I.O))h.allowAdFeatures=!1;!1===e(I.O)&&J("GTM",
27);k.name=b;h["&gtm"]=di(!0);h.hitCallback=d.s;var x=e(I.Re)||od("gtag.remote_config."+a+".url",2),z=e(I.Qe)||od("gtag.remote_config."+a+".dualId",2);x&&(k._x_19=x);z&&(k._x_20=z);g.fa=h;g.Ea=k;return g},tl=function(a,b){function c(v){var w=B(v);w.list=v.list_name;w.listPosition=v.list_position;w.position=v.list_position||v.creative_slot;w.creative=v.creative_name;return w}function d(v){for(var w=[],y=0;v&&y<v.length;y++)v[y]&&w.push(c(v[y]));return w.length?w:void 0}function e(v){return{id:g(I.Ya),
affiliation:g(I.Ke),revenue:g(I.Z),tax:g(I.Oe),shipping:g(I.Ne),coupon:g(I.Le),list:g(I.bc)||v}}for(var g=function(v){return b.getWithConfig(v)},h=g(I.Y),k,l=0;h&&l<h.length&&!(k=h[l][I.bc]);l++);var m=g("custom_map");if(Pa(m))for(var n=0;h&&n<h.length;++n){var q=h[n],u;for(u in m)m.hasOwnProperty(u)&&/^(dimension|metric)\d+$/.test(u)&&void 0!=m[u]&&yl(q,u,q[m[u]])}var p=null,r=g(I.Me);"purchase"===a||"refund"===a?p={action:a,cb:e(),Ka:d(h)}:"add_to_cart"===a?p={action:"add",Ka:d(h)}:"remove_from_cart"===
a?p={action:"remove",Ka:d(h)}:"view_item"===a?p={action:"detail",cb:e(k),Ka:d(h)}:"view_item_list"===a?p={action:"impressions",vg:d(h)}:"view_promotion"===a?p={action:"promo_view",Sc:d(r)}:"select_content"===a&&r&&0<r.length?p={action:"promo_click",Sc:d(r)}:"select_content"===a?p={action:"click",cb:{list:g(I.bc)||k},Ka:d(h)}:"begin_checkout"===a||"checkout_progress"===a?p={action:"checkout",Ka:d(h),cb:{step:"begin_checkout"===a?1:g(I.xd),option:g(I.wd)}}:"set_checkout_option"===a&&(p={action:"checkout_option",
cb:{step:g(I.xd),option:g(I.wd)}});p&&(p.Bh=g(I.ca));return p},Jl={},vl=function(a,b){var c=Jl[a];Jl[a]=B(b);if(!c)return!1;for(var d in b)if(b.hasOwnProperty(d)&&b[d]!==c[d])return!0;for(var e in c)if(c.hasOwnProperty(e)&&c[e]!==b[e])return!0;return!1};var Y={a:{}};

Y.a.gtagha=["google"],function(){var a=!1;var b=function(c){var d=c.vtp_conversionId,e=Hc,g=V("eventModel");if(a){hf(d.id,nl);if(e===I.w){var h=V("gtag.targets."+d.id);kf(h,d.id)}else jf(e,g,d.id);G(c.vtp_gtmOnSuccess)}else{var k=bf(af(We(g),c.vtp_gtmOnSuccess),c.vtp_gtmOnFailure);k.getWithConfig=function(l){return qd(l,d.containerId,d.id)};nl(d.id,e,(new Date).getTime(),
k)}};Y.__gtagha=b;Y.__gtagha.b="gtagha";Y.__gtagha.g=!0;Y.__gtagha.priorityOverride=0;}();
Y.a.e=["google"],function(){(function(a){Y.__e=a;Y.__e.b="e";Y.__e.g=!0;Y.__e.priorityOverride=0})(function(a){return String(wd(a.vtp_gtmEventId,"event"))})}();

Y.a.v=["google"],function(){(function(a){Y.__v=a;Y.__v.b="v";Y.__v.g=!0;Y.__v.priorityOverride=0})(function(a){var b=a.vtp_name;if(!b||!b.replace)return!1;var c=V(b.replace(/\\\./g,"."),a.vtp_dataLayerVersion||1);return void 0!==c?c:a.vtp_defaultValue})}();








Y.a.gtagaw=["google"],function(){var a=!1;a=!0;var b=function(c){var d=c.vtp_conversionId,e=void 0!==d.h[1]?d.id:void 0,g=Hc,h=V("eventModel");if(a){hf(c.vtp_conversionId.id,bl);if(g===I.w){var k=V("gtag.targets."+d.id);kf(k,c.vtp_conversionId.id)}else jf(g,h,d.id);G(c.vtp_gtmOnSuccess)}else{var l=bf(af(We(h),c.vtp_gtmOnSuccess),c.vtp_gtmOnFailure);l.getWithConfig=function(m){return qd(m,
d.containerId,e)};bl(c.vtp_conversionId.id,g,(new Date).getTime(),l)}};Y.__gtagaw=b;Y.__gtagaw.b="gtagaw";Y.__gtagaw.g=!0;Y.__gtagaw.priorityOverride=0;}();


Y.a.get=["google"],function(){var a=!1;a=!0;var b=function(c){if(c.vtp_isAutoTag){var d=String(c.vtp_trackingId),e=Hc||"";if(!a&&Nk(e))return;var g={};if(e===I.w){var h=V("gtag.targets."+d);B(h,g);a?g[I.ka]=!0:Ok(g);kf(g,d)}else{if(a){var k=V("eventModel");B(k,g);g[I.ka]=!0}else{var l;l=qd(I.Qa,d,void 0);if(ua(l))for(var m=0;m<l.length;m++){var n=l[m],q=qd(n,
d,void 0);void 0!==q&&(g[n]=q)}else{var u=V("eventModel");B(u,g)}Ok(g)}jf(e,g,d)}}else{var p=c.vtp_settings,r=p.eventParameters,v=p.userProperties;B(rj(c.vtp_eventParameters,"name","value"),r);B(rj(c.vtp_userProperties,"name","value"),v);r[I.V]=v;var w=String(c.vtp_eventName),y=c.vtp_allowSystemNames;if(!y&&Nk(w))return;y||Ok(r);(c.vtp_deferrable?Sk:Rk)(String(p.streamId),w,r)}c.vtp_gtmOnSuccess()};Y.__get=b;Y.__get.b="get";Y.__get.g=!0;Y.__get.priorityOverride=0;}();

Y.a.gtagfl=[],function(){function a(d){var e=/^DC-(\d+)(\/([\w-]+)\/([\w-]+)\+(\w+))?$/.exec(d);if(e)return{containerId:"DC-"+e[1],L:e[3]&&d}}var b=!1;var c=function(d){var e=d.vtp_targetId,g=Hc,h=V("eventModel");if(b){hf(e,hl);if(g===I.w){var k=V("gtag.targets."+e);kf(k,e)}else jf(g,h,e);G(d.vtp_gtmOnSuccess)}else{var l=a(e);if(l){var m=bf(af(We(h),d.vtp_gtmOnSuccess),
d.vtp_gtmOnFailure);m.getWithConfig=function(n){return qd(n,l.containerId,l.L)};hl(e,g,(new Date).getTime(),m)}else G(d.vtp_gtmOnFailure)}};Y.__gtagfl=c;Y.__gtagfl.b="gtagfl";Y.__gtagfl.g=!0;Y.__gtagfl.priorityOverride=0;}();


Y.a.gtaggf=["google"],function(){var a=!1;var b=function(c){var d=c.vtp_conversionId,e=Hc,g=V("eventModel");if(a){hf(d.id,kl);if(e===I.w){var h=V("gtag.targets."+d.id);kf(h,d.id)}else jf(e,g,d.id);G(c.vtp_gtmOnSuccess)}else{var k=bf(af(We(g),c.vtp_gtmOnSuccess),c.vtp_gtmOnFailure);k.getWithConfig=function(l){return qd(l,d.containerId,d.id)};kl(d.id,e,
(new Date).getTime(),k)}};Y.__gtaggf=b;Y.__gtaggf.b="gtaggf";Y.__gtaggf.g=!0;Y.__gtaggf.priorityOverride=0;}();




Y.a.gtagua=["google"],function(){var a=!1;var b=function(c){var d=c.vtp_trackingId,e=Hc,g=V("eventModel");if(a){hf(d,Cl);if(e===I.w){var h=V("gtag.targets."+d);kf(h,d)}else jf(e,g,d);G(c.vtp_gtmOnSuccess)}else{var k=bf(af(We(g),c.vtp_gtmOnSuccess),c.vtp_gtmOnFailure);k.getWithConfig=function(l){return qd(l,d,void 0)};Cl(d,e,(new Date).getTime(),k)}};Y.__gtagua=
b;Y.__gtagua.b="gtagua";Y.__gtagua.g=!0;Y.__gtagua.priorityOverride=0;}();


var Kl={};Kl.macro=function(a){if(Kg.sc.hasOwnProperty(a))return Kg.sc[a]},Kl.onHtmlSuccess=Kg.Qd(!0),Kl.onHtmlFailure=Kg.Qd(!1);Kl.dataLayer=pd;Kl.callback=function(a){Jc.hasOwnProperty(a)&&qa(Jc[a])&&Jc[a]();delete Jc[a]};Kl.Ff=function(){Ac[zc.m]=Kl;Ia(Kc,Y.a);xb=xb||Kg;yb=Td};
Kl.wg=function(){Fh.gtm_3pds=!0;Ac=D.google_tag_manager=D.google_tag_manager||{};if(Ac[zc.m]){var a=Ac.zones;a&&a.unregisterChild(zc.m)}else{for(var b=data.resource||{},c=b.macros||[],d=0;d<c.length;d++)pb.push(c[d]);for(var e=b.tags||[],g=0;g<e.length;g++)tb.push(e[g]);for(var h=b.predicates||[],
k=0;k<h.length;k++)rb.push(h[k]);for(var l=b.rules||[],m=0;m<l.length;m++){for(var n=l[m],q={},u=0;u<n.length;u++)q[n[u][0]]=Array.prototype.slice.call(n[u],1);qb.push(q)}vb=Y;wb=kj;(0,Kl.Ff)();ng();Wd=!1;Xd=0;if("interactive"==F.readyState&&!F.createEventObject||"complete"==F.readyState)Zd();else{$b(F,"DOMContentLoaded",Zd);$b(F,"readystatechange",Zd);if(F.createEventObject&&F.documentElement.doScroll){var p=!0;try{p=!D.frameElement}catch(y){}p&&$d()}$b(D,"load",Zd)}ag=!1;"complete"===F.readyState?
cg():$b(D,"load",cg);a:{if(!ed)break a;D.setInterval(fd,864E5);}
Gc=(new Date).getTime();Kl.bootstrap=Gc;}};(0,Kl.wg)();

})()